// Browser flow runtime, backed by the same Rust engine the desktop runs
// natively — compiled to WebAssembly in the `microflow-runtime-wasm` crate
// (single source of truth, no runtime logic duplicated in TS). The `.wasm` and
// its JS glue are generated by `wasm-pack` into ./generated (a build artifact;
// run `bun run build:wasm` — see apps/web/package.json).
//
// This module only loads the wasm and hands out a `FlowRuntime`. The transport
// (Web Serial read/write) and timers (`setTimeout` for wakeups) live in JS —
// see ../firmata/flow-reactor.ts — because WASM cannot block on Promises.
//
// The runtime-seam *types* are not declared here: they are generated from the
// Rust structs by ts-rs into @/lib/bindings and only re-exported below, so the
// two languages cannot drift.

import init, {
  FlowRuntime,
  figmaAnnounceActions as figmaAnnounceActionsRaw,
} from "./generated/microflow_runtime_wasm.js";
// `?url` asks Vite to emit the wasm as a hashed asset and hand us its URL.
import wasmUrl from "./generated/microflow_runtime_wasm_bg.wasm?url";
import type { FigmaPublish } from "@/lib/bindings/FigmaPublish";
import { lazyWasmInit } from "@/lib/wasm-init";

export { FlowRuntime };

/** Lazily instantiate the wasm module exactly once; concurrent callers share it. */
export const ensureRuntimeReady = lazyWasmInit(init, wasmUrl);

/** Create a fresh flow runtime for one board connection. */
export async function createFlowRuntime(): Promise<FlowRuntime> {
  await ensureRuntimeReady();
  return new FlowRuntime();
}

/** One Figma plugin-handshake publish a host must make. */
export type { FigmaPublish };

/** The Figma connect/disconnect publishes for a change in the live plugin-uid
 *  set (`prev`/`next` are `uid -> brokerId` maps). The handshake *protocol* —
 *  topics, payloads, retain — lives in core (`figma_announce_actions`), shared
 *  with the desktop host so both announce identically; this is the thin typed
 *  wrapper over the wasm binding. Requires the wasm module to be initialised
 *  (`ensureRuntimeReady` / `createFlowRuntime`), as every reconcile is. */
export function figmaAnnounceActions(
  prev: Record<string, string>,
  next: Record<string, string>,
): FigmaPublish[] {
  return JSON.parse(
    figmaAnnounceActionsRaw(JSON.stringify(prev), JSON.stringify(next)),
  ) as FigmaPublish[];
}

/** One emitted component event. */
export type { ComponentEvent } from "@/lib/bindings/ComponentEvent";

/** A timer the host must arm; on fire, call `runtime.wake(nodeId, method, now)`. */
export type { Wakeup } from "@/lib/bindings/Wakeup";

/** An outbound cloud call the host must perform (`kind`-tagged, `source` is the
 *  issuing node id). The result, if any, re-enters the runtime via its inject
 *  path. */
export type { CloudRequest } from "@/lib/bindings/CloudRequest";

/** One MIDI in-node's device interest, as returned by `runtime.midiListeners()`.
 *  `deviceName` is a case-insensitive substring filter on the host port name;
 *  "" = every device. */
export type { MidiListener } from "@/lib/bindings/MidiListener";

/** A node's runtime health signal, shown on its UI badge. `message: null` clears
 *  the node's diagnostic. */
export type { NodeDiagnostic } from "@/lib/bindings/NodeDiagnostic";

/** The side effects of one runtime turn. */
export type { Effects } from "@/lib/bindings/Effects";
