// Browser flow runtime, backed by the same Rust engine the desktop runs
// natively — compiled to WebAssembly in the `microflow-runtime-wasm` crate
// (single source of truth, no runtime logic duplicated in TS). The `.wasm` and
// its JS glue are generated by `wasm-pack` into ./generated (a build artifact;
// run `bun run build:wasm` — see apps/web/package.json).
//
// This module only loads the wasm and hands out a `FlowRuntime`. The transport
// (Web Serial read/write) and timers (`setTimeout` for wakeups) live in JS —
// see ../firmata/flow-reactor.ts — because WASM cannot block on Promises.

import init, { FlowRuntime } from "./generated/microflow_runtime_wasm.js";
// `?url` asks Vite to emit the wasm as a hashed asset and hand us its URL.
import wasmUrl from "./generated/microflow_runtime_wasm_bg.wasm?url";
import type { ComponentValue } from "@/lib/bindings/ComponentValue";

export { FlowRuntime };

/** Lazily instantiate the wasm module exactly once; concurrent callers share it. */
let initPromise: Promise<unknown> | null = null;
export function ensureRuntimeReady(): Promise<unknown> {
  if (initPromise === null) {
    initPromise = init({ module_or_path: wasmUrl });
  }
  return initPromise;
}

/** Create a fresh flow runtime for one board connection. */
export async function createFlowRuntime(): Promise<FlowRuntime> {
  await ensureRuntimeReady();
  return new FlowRuntime();
}

/** One emitted component event (matches the Rust `ComponentEvent` serde shape). */
export type ComponentEvent = {
  source: string;
  sourceHandle: string;
  value: ComponentValue;
  edgeId: string | null;
  sequence: number;
};

/** A timer the host must arm; on fire, call `runtime.wake(nodeId, method, now)`. */
export type Wakeup = {
  id: number;
  nodeId: string;
  method: string;
  delayMs: number;
};

/** The side effects of one runtime turn (matches the Rust `Effects` serde shape). */
export type Effects = {
  outboundBytes: number[];
  componentEvents: ComponentEvent[];
  wakeups: Wakeup[];
  cancellations: number[];
};
