// Browser flow runtime, backed by the same Rust engine the desktop runs
// natively — compiled to WebAssembly in the `microflow-runtime-wasm` crate
// (single source of truth, no runtime logic duplicated in TS). The `.wasm` and
// its JS glue are generated by `wasm-pack` into ./generated (a build artifact;
// run `bun run build:wasm` — see apps/web/package.json).
//
// This module only loads the wasm and hands out a `FlowRuntime`. The transport
// (Web Serial read/write) and timers (`setTimeout` for wakeups) live in JS —
// see ../firmata/flow-reactor.ts — because WASM cannot block on Promises.

import init, {
  FlowRuntime,
  figmaAnnounceActions as figmaAnnounceActionsRaw,
} from "./generated/microflow_runtime_wasm.js";
// `?url` asks Vite to emit the wasm as a hashed asset and hand us its URL.
import wasmUrl from "./generated/microflow_runtime_wasm_bg.wasm?url";
import type { ComponentValue } from "@/lib/bindings/ComponentValue";

export { FlowRuntime };

/** Lazily instantiate the wasm module exactly once; concurrent callers share it. */
let initPromise: Promise<unknown> | null = null;
export function ensureRuntimeReady(): Promise<unknown> {
  if (initPromise === null) {
    initPromise = init({ module_or_path: wasmUrl });
  }
  return initPromise;
}

/** Create a fresh flow runtime for one board connection. */
export async function createFlowRuntime(): Promise<FlowRuntime> {
  await ensureRuntimeReady();
  return new FlowRuntime();
}

/** One Figma plugin-handshake publish a host must make (the Rust `FigmaPublish`
 *  serde shape). */
export type FigmaPublish = {
  brokerId: string;
  topic: string;
  payload: string;
  retain: boolean;
};

/** The Figma connect/disconnect publishes for a change in the live plugin-uid
 *  set (`prev`/`next` are `uid -> brokerId` maps). The handshake *protocol* —
 *  topics, payloads, retain — lives in core (`figma_announce_actions`), shared
 *  with the desktop host so both announce identically; this is the thin typed
 *  wrapper over the wasm binding. Requires the wasm module to be initialised
 *  (`ensureRuntimeReady` / `createFlowRuntime`), as every reconcile is. */
export function figmaAnnounceActions(
  prev: Record<string, string>,
  next: Record<string, string>,
): FigmaPublish[] {
  return JSON.parse(
    figmaAnnounceActionsRaw(JSON.stringify(prev), JSON.stringify(next)),
  ) as FigmaPublish[];
}

/** One emitted component event (matches the Rust `ComponentEvent` serde shape). */
export type ComponentEvent = {
  source: string;
  sourceHandle: string;
  value: ComponentValue;
  edgeId: string | null;
  sequence: number;
};

/** A timer the host must arm; on fire, call `runtime.wake(nodeId, method, now)`. */
export type Wakeup = {
  id: number;
  nodeId: string;
  method: string;
  delayMs: number;
};

/** An outbound cloud call the host must perform (matches the Rust `CloudRequest`
 *  serde shape: `kind`-tagged, `source` is the issuing node id). The result, if
 *  any, re-enters the runtime via its inject path. */
export type CloudRequest = { source: string } & (
  | { kind: "mqttPublish"; brokerId: string; topic: string; payload: number[]; retain: boolean }
  | {
      kind: "llmGenerate";
      providerId: string;
      model: string;
      system: string | null;
      prompt: string;
    }
  | { kind: "midiSend"; deviceName: string; bytes: number[] }
);

/** One MIDI in-node's device interest (matches the Rust `MidiListener` serde
 *  shape, as returned by `runtime.midiListeners()`). `deviceName` is a
 *  case-insensitive substring filter on the host port name; "" = every device. */
export type MidiListener = {
  nodeId: string;
  deviceName: string;
};

/** The side effects of one runtime turn (matches the Rust `Effects` serde shape). */
export type Effects = {
  outboundBytes: number[];
  componentEvents: ComponentEvent[];
  wakeups: Wakeup[];
  cancellations: number[];
  cloudRequests: CloudRequest[];
};
