//! Component Registry
//!
//! Provides a centralized way to create components by name. The catalog of
//! `register_*` calls is generated by `build.rs` from `node-components.json`
//! and included into [`ComponentRegistry::register_all`] below.
//!
//! Each catalog entry compiles to either
//! `self.register::<Type>("Name", &[...ports])` (software) or
//! `self.register_hardware::<Type>("Name", &[...ports])` (`requiresHardware:
//! true`). The hardware variant adds a [`HardwareComponent`] bound so a
//! catalog flag drift — e.g., an entry marked `requiresHardware: true` whose
//! impl forgot the `HardwareComponent` trait — fails to compile.
//!
//! The `ports` slice is the catalog-declared **Port** set. `register` /
//! `register_hardware` assert it equals `B::ports()`, so a drift between
//! `node-components.json impls[].ports[]` and the Rust impl's declared
//! `fn ports()` panics at registry construction. See `CONTEXT.md` § Port and
//! ADR-0001.

use super::base::{BoardHandle, Component, ComponentEvent};
use super::component::{ComponentBuilder, HardwareComponent};
use super::services::{FromServices, RuntimeServices};
use crate::error::RuntimeError;
use serde::Deserialize;
use std::sync::Arc;
use tokio::sync::mpsc;

/// Boxed builder closure: deserializes a config off the catalog node `data`,
/// projects the impl's typed `Deps` slice out of [`RuntimeServices`], and
/// produces a constructed `Box<dyn Component>`. Errors out with
/// [`RuntimeError::ConfigDeserialize`] if the JSON doesn't match the
/// builder's `Config` type — no silent `Default` fallback.
type Factory = Box<
    dyn Fn(
            String,
            &serde_json::Value,
            &RuntimeServices,
        ) -> Result<Box<dyn Component>, RuntimeError>
        + Send
        + Sync,
>;

/// Component registry for creating components by instance name.
pub struct ComponentRegistry {
    entries: std::collections::HashMap<&'static str, Factory>,
}

impl ComponentRegistry {
    pub fn new() -> Self {
        let mut registry = Self {
            entries: std::collections::HashMap::new(),
        };
        registry.register_all();
        registry
    }

    /// Create a component by instance name.
    pub fn create(
        &self,
        id: &str,
        instance: &str,
        data: &serde_json::Value,
        services: &RuntimeServices,
        event_sender: mpsc::UnboundedSender<ComponentEvent>,
        board_handle: Arc<BoardHandle>,
    ) -> Result<Box<dyn Component>, RuntimeError> {
        let factory = self.entries.get(instance).ok_or_else(|| {
            RuntimeError::ComponentNotFound(format!("Unknown component type: {instance}"))
        })?;

        let mut component = factory(id.to_string(), data, services)?;
        component.set_event_sender(event_sender);

        // Initialize only when the component is hardware-bound and the board is
        // already connected. Software components return `None` from
        // `as_hardware_mut` and skip this path entirely.
        if board_handle.is_connected() {
            if let Some(hw) = component.as_hardware_mut() {
                hw.initialize(board_handle)?;
            }
        }

        Ok(component)
    }

    /// Check if a component type exists.
    #[allow(dead_code)]
    pub fn exists(&self, instance: &str) -> bool {
        self.entries.contains_key(instance)
    }

    /// List of all registered component types.
    #[allow(dead_code)]
    pub fn component_types(&self) -> Vec<&'static str> {
        self.entries.keys().copied().collect()
    }

    fn register_all(&mut self) {
        include!(concat!(env!("OUT_DIR"), "/register_all_body.rs"));
    }

    /// Register a software-only Component Catalog entry. Used by the
    /// `build.rs`-generated body inside [`register_all`].
    fn register<B: ComponentBuilder>(&mut self, name: &'static str, catalog_ports: &'static [&'static str]) {
        assert_ports_match::<B>(name, catalog_ports);
        self.entries.insert(name, make_factory::<B>(name));
    }

    /// Register a hardware-bound Component Catalog entry. The
    /// `B: HardwareComponent` bound asserts at compile time that the impl
    /// implements [`HardwareComponent`], catching catalog/impl drift.
    fn register_hardware<B: ComponentBuilder + HardwareComponent>(
        &mut self,
        name: &'static str,
        catalog_ports: &'static [&'static str],
    ) {
        assert_ports_match::<B>(name, catalog_ports);
        self.entries.insert(name, make_factory::<B>(name));
    }
}

/// Assert the Rust impl's declared **Port** set equals the catalog's. A drift
/// would mean a flow edge could target a handle the impl ignores, or that
/// `node-components.json impls[].ports[]` is missing a Port the impl actually
/// handles. Both are silent footguns in the absence of this check.
fn assert_ports_match<B: Component>(name: &'static str, catalog_ports: &'static [&'static str]) {
    let rust_ports = B::ports();
    assert_eq!(
        rust_ports, catalog_ports,
        "Port drift for component {name:?}: \
         Rust impl declares {rust_ports:?}, \
         node-components.json declares {catalog_ports:?}. \
         Update both to match — see CONTEXT.md § Port."
    );
}

/// Build a [`Factory`] closure that captures the catalog name for use in
/// [`RuntimeError::ConfigDeserialize`] when deserialization fails.
///
/// The closure projects each impl's typed [`ComponentBuilder::Deps`] out of
/// the active [`RuntimeServices`] via [`FromServices`], so the builder
/// receives exactly the slice it declared (an `Arc<LlmRegistry>` for
/// `Llm`, `()` for the 29 components that need nothing, etc.).
fn make_factory<B: ComponentBuilder>(name: &'static str) -> Factory {
    Box::new(move |id, data, services| {
        let config = B::Config::deserialize(data).map_err(|e| {
            RuntimeError::ConfigDeserialize {
                component: name.to_string(),
                source: e,
            }
        })?;
        let deps = <B::Deps as FromServices>::from_services(services);
        let component = B::build(id, config, deps)?;
        Ok(Box::new(component) as Box<dyn Component>)
    })
}

impl Default for ComponentRegistry {
    fn default() -> Self {
        Self::new()
    }
}
