//! Component Registry
//!
//! Provides a centralized way to create components by name. The catalogue of
//! `register_*` calls is generated by `build.rs` from `node-components.json`
//! and included into [`ComponentRegistry::register_all`] below.

use super::base::{BoardHandle, Component, ComponentEvent};
use super::context::RuntimeContext;
use crate::error::RuntimeError;
use std::sync::Arc;
use tokio::sync::mpsc;

use serde::Deserialize;

/// Deserialize a config from a `&serde_json::Value` without cloning.
/// Falls back to `Default` on parse failure.
fn parse_config<'de, T: Deserialize<'de> + Default>(data: &'de serde_json::Value) -> T {
    T::deserialize(data).unwrap_or_default()
}

/// Factory function type for creating components
type ComponentFactory = fn(id: String, data: &serde_json::Value, ctx: &RuntimeContext) -> Box<dyn Component>;

/// Registry entry with factory and metadata
struct RegistryEntry {
    factory: ComponentFactory,
    requires_hardware: bool,
}

/// Component registry for creating components by instance name
pub struct ComponentRegistry {
    entries: std::collections::HashMap<&'static str, RegistryEntry>,
}

impl ComponentRegistry {
    pub fn new() -> Self {
        let mut registry = Self {
            entries: std::collections::HashMap::new(),
        };
        registry.register_all();
        registry
    }

    /// Create a component by instance name
    pub fn create(
        &self,
        id: &str,
        instance: &str,
        data: &serde_json::Value,
        ctx: &RuntimeContext,
        event_sender: mpsc::UnboundedSender<ComponentEvent>,
        board_handle: Arc<BoardHandle>,
    ) -> Result<Box<dyn Component>, RuntimeError> {
        let entry = self.entries.get(instance)
            .ok_or_else(|| RuntimeError::ComponentNotFound(format!("Unknown component type: {instance}")))?;

        let mut component = (entry.factory)(id.to_string(), data, ctx);
        component.set_event_sender(event_sender);

        // Initialize hardware components if board is connected
        if entry.requires_hardware && board_handle.is_connected() {
            component.initialize(board_handle)?;
        }

        Ok(component)
    }

    /// Check if a component type exists
    #[allow(dead_code)]
    pub fn exists(&self, instance: &str) -> bool {
        self.entries.contains_key(instance)
    }

    /// Get list of all registered component types
    #[allow(dead_code)]
    pub fn component_types(&self) -> Vec<&'static str> {
        self.entries.keys().copied().collect()
    }

    fn register_all(&mut self) {
        include!(concat!(env!("OUT_DIR"), "/register_all_body.rs"));
    }

    fn register_hardware(&mut self, name: &'static str, factory: ComponentFactory) {
        self.entries.insert(name, RegistryEntry { factory, requires_hardware: true });
    }

    fn register_software(&mut self, name: &'static str, factory: ComponentFactory) {
        self.entries.insert(name, RegistryEntry { factory, requires_hardware: false });
    }
}

impl Default for ComponentRegistry {
    fn default() -> Self {
        Self::new()
    }
}
