/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as CircuitRouteImport } from './routes/circuit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowLocalRouteImport } from './routes/flow/local'
import { Route as FlowFlowIdRouteImport } from './routes/flow/$flowId'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitRoute = CircuitRouteImport.update({
  id: '/circuit',
  path: '/circuit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowLocalRoute = FlowLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => FlowRoute,
} as any)
const FlowFlowIdRoute = FlowFlowIdRouteImport.update({
  id: '/$flowId',
  path: '/$flowId',
  getParentRoute: () => FlowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circuit': typeof CircuitRoute
  '/flow': typeof FlowRouteWithChildren
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/flow/$flowId': typeof FlowFlowIdRoute
  '/flow/local': typeof FlowLocalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circuit': typeof CircuitRoute
  '/flow': typeof FlowRouteWithChildren
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/flow/$flowId': typeof FlowFlowIdRoute
  '/flow/local': typeof FlowLocalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circuit': typeof CircuitRoute
  '/flow': typeof FlowRouteWithChildren
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/flow/$flowId': typeof FlowFlowIdRoute
  '/flow/local': typeof FlowLocalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circuit'
    | '/flow'
    | '/login'
    | '/success'
    | '/flow/$flowId'
    | '/flow/local'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circuit'
    | '/flow'
    | '/login'
    | '/success'
    | '/flow/$flowId'
    | '/flow/local'
  id:
    | '__root__'
    | '/'
    | '/circuit'
    | '/flow'
    | '/login'
    | '/success'
    | '/flow/$flowId'
    | '/flow/local'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircuitRoute: typeof CircuitRoute
  FlowRoute: typeof FlowRouteWithChildren
  LoginRoute: typeof LoginRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuit': {
      id: '/circuit'
      path: '/circuit'
      fullPath: '/circuit'
      preLoaderRoute: typeof CircuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/local': {
      id: '/flow/local'
      path: '/local'
      fullPath: '/flow/local'
      preLoaderRoute: typeof FlowLocalRouteImport
      parentRoute: typeof FlowRoute
    }
    '/flow/$flowId': {
      id: '/flow/$flowId'
      path: '/$flowId'
      fullPath: '/flow/$flowId'
      preLoaderRoute: typeof FlowFlowIdRouteImport
      parentRoute: typeof FlowRoute
    }
  }
}

interface FlowRouteChildren {
  FlowFlowIdRoute: typeof FlowFlowIdRoute
  FlowLocalRoute: typeof FlowLocalRoute
}

const FlowRouteChildren: FlowRouteChildren = {
  FlowFlowIdRoute: FlowFlowIdRoute,
  FlowLocalRoute: FlowLocalRoute,
}

const FlowRouteWithChildren = FlowRoute._addFileChildren(FlowRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircuitRoute: CircuitRoute,
  FlowRoute: FlowRouteWithChildren,
  LoginRoute: LoginRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
