import type { Template } from "../types";
import { buttonData, ledData, counterData } from "../data-factories";

export const simonSays: Template = {
  id: "simon-says",
  name: "Memory Game",
  description:
    "A button-based memory game. Press buttons in sequence and track your score!",
  difficulty: "advanced",
  categories: ["Games", "Fun", "Hardware"],
  nodes: [
    {
      id: "button-1",
      type: "Button",
      position: { x: 100, y: 100 },
      data: { ...buttonData(6), label: "Red" },
    },
    {
      id: "button-2",
      type: "Button",
      position: { x: 100, y: 300 },
      data: { ...buttonData(7), label: "Blue" },
    },
    {
      id: "button-3",
      type: "Button",
      position: { x: 100, y: 500 },
      data: { ...buttonData(8), label: "Green" },
    },
    {
      id: "led-1",
      type: "Led",
      position: { x: 500, y: 100 },
      data: { ...ledData(9), label: "Red LED" },
    },
    {
      id: "led-2",
      type: "Led",
      position: { x: 500, y: 300 },
      data: { ...ledData(10), label: "Blue LED" },
    },
    {
      id: "led-3",
      type: "Led",
      position: { x: 500, y: 500 },
      data: { ...ledData(11), label: "Green LED" },
    },
    {
      id: "counter-1",
      type: "Counter",
      position: { x: 900, y: 300 },
      data: { ...counterData(), label: "Score" },
    },
  ],
  edges: [
    {
      id: "e-btn1-led1",
      source: "button-1",
      target: "led-1",
      sourceHandle: "active",
      targetHandle: "turnOn",
      type: "animated",
    },
    {
      id: "e-btn1-led1-off",
      source: "button-1",
      target: "led-1",
      sourceHandle: "inactive",
      targetHandle: "turnOff",
      type: "animated",
    },
    {
      id: "e-btn2-led2",
      source: "button-2",
      target: "led-2",
      sourceHandle: "active",
      targetHandle: "turnOn",
      type: "animated",
    },
    {
      id: "e-btn2-led2-off",
      source: "button-2",
      target: "led-2",
      sourceHandle: "inactive",
      targetHandle: "turnOff",
      type: "animated",
    },
    {
      id: "e-btn3-led3",
      source: "button-3",
      target: "led-3",
      sourceHandle: "active",
      targetHandle: "turnOn",
      type: "animated",
    },
    {
      id: "e-btn3-led3-off",
      source: "button-3",
      target: "led-3",
      sourceHandle: "inactive",
      targetHandle: "turnOff",
      type: "animated",
    },
    {
      id: "e-btn1-counter",
      source: "button-1",
      target: "counter-1",
      sourceHandle: "active",
      targetHandle: "increment",
      type: "animated",
    },
    {
      id: "e-btn2-counter",
      source: "button-2",
      target: "counter-1",
      sourceHandle: "active",
      targetHandle: "increment",
      type: "animated",
    },
    {
      id: "e-btn3-counter",
      source: "button-3",
      target: "counter-1",
      sourceHandle: "active",
      targetHandle: "increment",
      type: "animated",
    },
  ],
};
