// Browser Firmata protocol, backed by the same Rust codec the desktop app runs
// natively — compiled to WebAssembly in the `microflow-firmata-wasm` crate
// (single source of truth, no protocol logic duplicated in TS). The `.wasm` and
// its JS glue are generated by `wasm-pack` into ./generated (a build artifact;
// run `bun run build:wasm` — see apps/web/package.json).
//
// This module only loads the wasm and hands out a `FirmataSession` (the codec).
// The actual transport — opening a port, the async read/write loop — lives in
// ./web-serial.ts, because WASM cannot block on the Web Serial Promises.

import init, {
  FirmataSession,
  parseHex as wasmParseHex,
  detectBoardFromUsb as wasmDetectBoardFromUsb,
} from "./generated/microflow_firmata_wasm.js";
// `?url` asks Vite to emit the wasm as a hashed asset and hand us its URL, so it
// loads correctly in dev and after a production build with no extra Vite plugin.
import wasmUrl from "./generated/microflow_firmata_wasm_bg.wasm?url";

export { FirmataSession };

/** Lazily instantiate the wasm module exactly once; concurrent callers share it. */
let initPromise: Promise<unknown> | null = null;
export function ensureFirmataReady(): Promise<unknown> {
  if (initPromise === null) {
    initPromise = init({ module_or_path: wasmUrl });
  }
  return initPromise;
}

/** Create a fresh protocol session for one board connection. */
export async function createSession(): Promise<FirmataSession> {
  await ensureFirmataReady();
  return new FirmataSession();
}

/** Parse an Intel HEX string into the raw flash image (gaps filled with 0xFF). */
export async function parseHex(hexContent: string): Promise<Uint8Array> {
  await ensureFirmataReady();
  return wasmParseHex(hexContent);
}

/** Map a USB vendor/product id to a board id (e.g. "uno"), or undefined. */
export async function detectBoardFromUsb(
  vid: number,
  pid: number,
): Promise<string | undefined> {
  await ensureFirmataReady();
  return wasmDetectBoardFromUsb(vid, pid);
}

/** The shape `FirmataSession.feed()` returns (parsed from its JSON string). */
export type FeedResult = {
  pinChanges: { pin: number; value: number; isAnalog: boolean }[];
  i2cReplies: { address: number; register: number; data: number[] }[];
  firmwareUpdated: boolean;
  capabilitiesUpdated: boolean;
};
