// Browser Firmata protocol, backed by the same Rust codec the desktop app runs
// natively — compiled to WebAssembly in the `microflow-firmata-wasm` crate
// (single source of truth, no protocol logic duplicated in TS). The `.wasm` and
// its JS glue are generated by `wasm-pack` into ./generated (a build artifact;
// run `bun run build:wasm` — see apps/web/package.json).
//
// This module only loads the wasm and hands out a `FirmataSession` (the codec).
// The actual transport — opening a port, the async read/write loop — lives in
// ./web-serial.ts, because WASM cannot block on the Web Serial Promises.

import init, {
  BringUpMachine,
  FirmataSession,
  FlashSession,
  parseHex as wasmParseHex,
  detectBoardFromUsb as wasmDetectBoardFromUsb,
  standardFirmataHex as wasmStandardFirmataHex,
  flashBaud as wasmFlashBaud,
} from "./generated/microflow_firmata_wasm.js";
// `?url` asks Vite to emit the wasm as a hashed asset and hand us its URL, so it
// loads correctly in dev and after a production build with no extra Vite plugin.
import wasmUrl from "./generated/microflow_firmata_wasm_bg.wasm?url";
import type { BringUpAction } from "@/lib/bindings/BringUpAction";
import type { BringUpEvent } from "@/lib/bindings/BringUpEvent";
import type { FlashStep } from "@/lib/bindings/FlashStep";
import type { PinInfo } from "@/lib/bindings/PinInfo";
import { lazyWasmInit } from "@/lib/wasm-init";

export { BringUpMachine, FirmataSession, FlashSession };

// --- Bring-up policy (microflow_core::bringup, shared with the desktop) -----

/** An event fed into the shared bring-up state machine. */
export type { BringUpEvent } from "@/lib/bindings/BringUpEvent";

/** A UI-facing bring-up phase; the adapter maps it onto `BoardState`. */
export type { BringUpPhase } from "@/lib/bindings/BringUpPhase";

/** An action the machine tells the host to perform, in order. */
export type { BringUpAction } from "@/lib/bindings/BringUpAction";

/** Create the shared bring-up state machine (the policy lives in Rust). */
export async function createBringUp(): Promise<BringUpMachine> {
  await ensureFirmataReady();
  return new BringUpMachine();
}

/** Feed one event into the machine; returns the actions the host must perform,
 *  in order. The JSON crossing lives here, not at the call site. */
export function handleBringUp(machine: BringUpMachine, event: BringUpEvent): BringUpAction[] {
  return JSON.parse(machine.handle(JSON.stringify(event))) as BringUpAction[];
}

/** Create a flashing session for a board id + raw flash image. */
export async function createFlashSession(
  boardId: string,
  flash: Uint8Array,
): Promise<FlashSession> {
  await ensureFirmataReady();
  return new FlashSession(boardId, flash);
}

/** The embedded StandardFirmata hex for a board id, or undefined. */
export async function standardFirmataHex(boardId: string): Promise<string | undefined> {
  await ensureFirmataReady();
  return wasmStandardFirmataHex(boardId);
}

/** The baud rate to open the port at when flashing a board id. */
export async function flashBaud(boardId: string): Promise<number | undefined> {
  await ensureFirmataReady();
  return wasmFlashBaud(boardId);
}

/** A `FlashStep` emitted by a `FlashSession` (parsed from its JSON). */
export type { FlashStep } from "@/lib/bindings/FlashStep";

/** Start a flash session's step machine. */
export function flashStart(session: FlashSession): FlashStep {
  return JSON.parse(session.start()) as FlashStep;
}

/** Advance a flash session with the bytes the last step read. */
export function flashAdvance(session: FlashSession, input: Uint8Array): FlashStep {
  return JSON.parse(session.advance(input)) as FlashStep;
}

/** Lazily instantiate the wasm module exactly once; concurrent callers share it. */
export const ensureFirmataReady = lazyWasmInit(init, wasmUrl);

/** Create a fresh protocol session for one board connection. */
export async function createSession(): Promise<FirmataSession> {
  await ensureFirmataReady();
  return new FirmataSession();
}

/** The pin table a session has discovered so far (parsed from its JSON). */
export function sessionPins(session: FirmataSession): PinInfo[] {
  return JSON.parse(session.pinsJson()) as PinInfo[];
}

/** Parse an Intel HEX string into the raw flash image (gaps filled with 0xFF). */
export async function parseHex(hexContent: string): Promise<Uint8Array> {
  await ensureFirmataReady();
  return wasmParseHex(hexContent);
}

/** Map a USB vendor/product id to a board id (e.g. "uno"), or undefined. */
export async function detectBoardFromUsb(
  vid: number,
  pid: number,
): Promise<string | undefined> {
  await ensureFirmataReady();
  return wasmDetectBoardFromUsb(vid, pid);
}

/** The shape `FirmataSession.feed()` returns (parsed from its JSON string). */
export type { FeedResult } from "@/lib/bindings/FeedResult";
