// Browser Firmata protocol, backed by the same Rust codec the desktop app runs
// natively — compiled to WebAssembly in the `microflow-firmata-wasm` crate
// (single source of truth, no protocol logic duplicated in TS). The `.wasm` and
// its JS glue are generated by `wasm-pack` into ./generated (a build artifact;
// run `bun run build:wasm` — see apps/web/package.json).
//
// This module only loads the wasm and hands out a `FirmataSession` (the codec).
// The actual transport — opening a port, the async read/write loop — lives in
// ./web-serial.ts, because WASM cannot block on the Web Serial Promises.

import init, {
  BringUpMachine,
  FirmataSession,
  FlashSession,
  parseHex as wasmParseHex,
  detectBoardFromUsb as wasmDetectBoardFromUsb,
  standardFirmataHex as wasmStandardFirmataHex,
  flashBaud as wasmFlashBaud,
} from "./generated/microflow_firmata_wasm.js";
// `?url` asks Vite to emit the wasm as a hashed asset and hand us its URL, so it
// loads correctly in dev and after a production build with no extra Vite plugin.
import wasmUrl from "./generated/microflow_firmata_wasm_bg.wasm?url";

export { BringUpMachine, FirmataSession, FlashSession };

// --- Bring-up policy (microflow_core::bringup, shared with the desktop) -----

/** An event fed into the shared bring-up state machine. */
export type BringUpEvent =
  | { type: "portReady"; board: string | null; autoFlash: boolean; explicit: boolean }
  | { type: "probeOk" }
  | { type: "probeFailed" }
  | { type: "flashProgress"; done: number; total: number }
  | { type: "flashOk" }
  | { type: "flashFailed"; detail: string }
  | { type: "connectionLost" }
  | { type: "portGone" }
  | { type: "disconnectRequested" };

/** A UI-facing bring-up phase; the adapter maps it onto `BoardState`. */
export type BringUpPhase =
  | { kind: "disconnected" }
  | { kind: "connecting" }
  | { kind: "flashing"; board: string }
  | { kind: "connected" }
  | { kind: "error"; detail: string };

/** An action the machine tells the host to perform, in order. */
export type BringUpAction =
  | { type: "probe"; afterFlash: boolean }
  | { type: "flash"; board: string }
  | { type: "closePort" }
  | { type: "scheduleRetry" }
  | { type: "notify"; phase: BringUpPhase }
  | { type: "notifyFlashProgress"; percent: number };

/** Create the shared bring-up state machine (the policy lives in Rust). */
export async function createBringUp(): Promise<BringUpMachine> {
  await ensureFirmataReady();
  return new BringUpMachine();
}

/** Create a flashing session for a board id + raw flash image. */
export async function createFlashSession(
  boardId: string,
  flash: Uint8Array,
): Promise<FlashSession> {
  await ensureFirmataReady();
  return new FlashSession(boardId, flash);
}

/** The embedded StandardFirmata hex for a board id, or undefined. */
export async function standardFirmataHex(boardId: string): Promise<string | undefined> {
  await ensureFirmataReady();
  return wasmStandardFirmataHex(boardId);
}

/** The baud rate to open the port at when flashing a board id. */
export async function flashBaud(boardId: string): Promise<number | undefined> {
  await ensureFirmataReady();
  return wasmFlashBaud(boardId);
}

/** A `FlashStep` emitted by a `FlashSession` (parsed from its JSON). */
export type FlashStep =
  | { kind: "reset"; dtr: boolean; rts: boolean; delayMs: number }
  | { kind: "setBaud"; baud: number }
  | { kind: "flushInput" }
  | { kind: "transact"; write: number[]; readLen: number; timeoutMs: number }
  | { kind: "delay"; ms: number }
  | { kind: "reacquirePort"; waitMs: number; baud: number }
  | { kind: "progress"; done: number; total: number }
  | { kind: "done" }
  | { kind: "error"; message: string };

/** Lazily instantiate the wasm module exactly once; concurrent callers share it. */
let initPromise: Promise<unknown> | null = null;
export function ensureFirmataReady(): Promise<unknown> {
  if (initPromise === null) {
    initPromise = init({ module_or_path: wasmUrl });
  }
  return initPromise;
}

/** Create a fresh protocol session for one board connection. */
export async function createSession(): Promise<FirmataSession> {
  await ensureFirmataReady();
  return new FirmataSession();
}

/** Parse an Intel HEX string into the raw flash image (gaps filled with 0xFF). */
export async function parseHex(hexContent: string): Promise<Uint8Array> {
  await ensureFirmataReady();
  return wasmParseHex(hexContent);
}

/** Map a USB vendor/product id to a board id (e.g. "uno"), or undefined. */
export async function detectBoardFromUsb(
  vid: number,
  pid: number,
): Promise<string | undefined> {
  await ensureFirmataReady();
  return wasmDetectBoardFromUsb(vid, pid);
}

/** The shape `FirmataSession.feed()` returns (parsed from its JSON string). */
export type FeedResult = {
  pinChanges: { pin: number; value: number; isAnalog: boolean }[];
  i2cReplies: { address: number; register: number; data: number[] }[];
  firmwareUpdated: boolean;
  capabilitiesUpdated: boolean;
};
