// Generated by microflow v0.11.3.
// Target board: ESP32 (esp32).
// Sketch skeleton for 2 node(s).

// --- Includes ---
// Libraries not bundled with your board's core must be installed first:
// Arduino IDE > Sketch > Include Library > Manage Libraries…
#include <ESP32Servo.h>

// --- Declarations ---
// node sensor-1 (Sensor)
const uint8_t sensor_sensor_1_pin = 32; // A0
int sensor_sensor_1_value = 0;
// node servo-1 (Servo)
const uint8_t servo_servo_1_pin = 13;
Servo servo_servo_1;

void setup() {
  // --- Setup ---
  pinMode(sensor_sensor_1_pin, INPUT);
  servo_servo_1.attach(servo_servo_1_pin);
  servo_servo_1.write(90);
}

void loop() {
  static unsigned long previousMillis = 0;
  const unsigned long interval = 1; // ms; non-blocking scheduler tick
  unsigned long currentMillis = millis();
  if (currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;
    // --- Scheduled tasks ---
    sensor_sensor_1_value = analogRead(sensor_sensor_1_pin);
    servo_servo_1.write((int)constrain(((double)(sensor_sensor_1_value)), (double)0, (double)180));
  }
}
