// Generated by microflow v0.12.0.
// Target board: ESP32 (esp32).
// Sketch skeleton for 5 node(s).

// --- Includes ---
// Libraries not bundled with your board's core must be installed first:
// Arduino IDE > Sketch > Include Library > Manage Libraries…
#include <ArduinoJson.h>
#include <HTTPClient.h>
#include <PubSubClient.h>
#include <WiFi.h>
#include <WiFiClientSecure.h>

// --- Declarations ---
// WiFi credentials (Cloud Nodes)
const char* wifi_ssid = "golden-net";
const char* wifi_password = "golden-pass";
// node figma-1 (Figma)
#warning "Figma Node figma_figma_1: missing network credentials — using REPLACE_ME placeholder; set WiFi SSID and broker before flashing"
const char* figma_figma_1_broker = "REPLACE_ME";
const uint16_t figma_figma_1_port = 1883;
const char* figma_figma_1_client_id = "microflow-figma_figma_1";
WiFiClient figma_figma_1_wifi_client;
PubSubClient figma_figma_1_client(figma_figma_1_wifi_client);
const char* figma_figma_1_plugin_topic = "microflow//figma/variable/1-2";
const char* figma_figma_1_app_topic = "microflow//app/variable/1-2";
const char* figma_figma_1_set_topic = "microflow//app/variable/1-2/set";
String figma_figma_1_value;
void figma_figma_1_on_message(char* topic, byte* payload, unsigned int length) {
  figma_figma_1_value = String();
  for (unsigned int i = 0; i < length; i++) {
    figma_figma_1_value += (char)payload[i];
  }
}
void figma_figma_1_ensure_connected() {
  if (WiFi.status() != WL_CONNECTED) {
    return; // WiFi not up yet; retry on the next loop tick
  }
  if (!figma_figma_1_client.connected()) {
    figma_figma_1_client.setServer(figma_figma_1_broker, figma_figma_1_port);
    if (figma_figma_1_client.connect(figma_figma_1_client_id)) {
      figma_figma_1_client.subscribe(figma_figma_1_plugin_topic);
      figma_figma_1_client.subscribe(figma_figma_1_app_topic);
    }
  }
}
// node llm-1 (Llm)
const char* llm_llm_1_endpoint = "https://llm-surface.example.invalid";
const char* llm_llm_1_api_key = "sk-golden-fake";
const char* llm_llm_1_model = "test-model";
const char* llm_llm_1_prompt = "Say hi";
const char* llm_llm_1_system = "Be brief";
String llm_llm_1_value;
void llm_llm_1_request() {
  if (WiFi.status() != WL_CONNECTED) {
    return; // WiFi not up yet; retry on the next loop tick
  }
  WiFiClientSecure client;
  client.setInsecure();
  HTTPClient http;
  String url = String(llm_llm_1_endpoint) + "/v1/chat/completions";
  if (!http.begin(client, url)) {
    return; // could not start the request; retry next tick
  }
  http.addHeader("Content-Type", "application/json");
  http.addHeader("Authorization", String("Bearer ") + llm_llm_1_api_key);
  JsonDocument requestDoc;
  requestDoc["model"] = llm_llm_1_model;
  JsonArray messages = requestDoc["messages"].to<JsonArray>();
  if (strlen(llm_llm_1_system) > 0) {
    JsonObject sys = messages.add<JsonObject>();
    sys["role"] = "system";
    sys["content"] = llm_llm_1_system;
  }
  JsonObject user = messages.add<JsonObject>();
  user["role"] = "user";
  user["content"] = llm_llm_1_prompt;
  String requestBody;
  serializeJson(requestDoc, requestBody);
  int status = http.POST(requestBody);
  if (status == HTTP_CODE_OK) {
    JsonDocument responseDoc;
    if (deserializeJson(responseDoc, http.getStream()) == DeserializationError::Ok) {
      llm_llm_1_value = responseDoc["choices"][0]["message"]["content"].as<String>();
    }
  }
  http.end();
}
double llm_llm_1_trigger_prev0 = 0.0;
// node monitor-1 (Monitor)
#warning "Monitor Node monitor_monitor_1: missing network credentials — using REPLACE_ME placeholder; set WiFi SSID and broker before flashing"
const char* monitor_monitor_1_broker = "REPLACE_ME";
const uint16_t monitor_monitor_1_port = 1883;
const char* monitor_monitor_1_client_id = "microflow-monitor_monitor_1";
WiFiClient monitor_monitor_1_wifi_client;
PubSubClient monitor_monitor_1_client(monitor_monitor_1_wifi_client);
const char* monitor_monitor_1_topic = "microflow//monitor/monitor_1";
String monitor_monitor_1_last_published;
void monitor_monitor_1_ensure_connected() {
  if (WiFi.status() != WL_CONNECTED) {
    return; // WiFi not up yet; retry on the next loop tick
  }
  if (!monitor_monitor_1_client.connected()) {
    monitor_monitor_1_client.setServer(monitor_monitor_1_broker, monitor_monitor_1_port);
    if (monitor_monitor_1_client.connect(monitor_monitor_1_client_id)) {
      // no inbound topics to subscribe
    }
  }
}
// node mqtt-pub (Mqtt)
const char* mqtt_mqtt_pub_broker = "broker-surface.example.invalid";
const uint16_t mqtt_mqtt_pub_port = 1883;
const char* mqtt_mqtt_pub_topic = "microflow/out";
const char* mqtt_mqtt_pub_client_id = "microflow-mqtt_pub";
WiFiClient mqtt_mqtt_pub_wifi_client;
PubSubClient mqtt_mqtt_pub_client(mqtt_mqtt_pub_wifi_client);
void mqtt_mqtt_pub_ensure_connected() {
  if (WiFi.status() != WL_CONNECTED) {
    return; // WiFi not up yet; retry on the next loop tick
  }
  if (!mqtt_mqtt_pub_client.connected()) {
    mqtt_mqtt_pub_client.setServer(mqtt_mqtt_pub_broker, mqtt_mqtt_pub_port);
    if (mqtt_mqtt_pub_client.connect(mqtt_mqtt_pub_client_id)) {
      // publish-only Node: nothing to subscribe
    }
  }
}
String mqtt_mqtt_pub_trigger_prev0 = "";
// node mqtt-sub (Mqtt)
const char* mqtt_mqtt_sub_broker = "broker-surface.example.invalid";
const uint16_t mqtt_mqtt_sub_port = 1883;
const char* mqtt_mqtt_sub_topic = "microflow/in";
const char* mqtt_mqtt_sub_client_id = "microflow-mqtt_sub";
WiFiClient mqtt_mqtt_sub_wifi_client;
PubSubClient mqtt_mqtt_sub_client(mqtt_mqtt_sub_wifi_client);
String mqtt_mqtt_sub_value;
void mqtt_mqtt_sub_on_message(char* topic, byte* payload, unsigned int length) {
  mqtt_mqtt_sub_value = String();
  for (unsigned int i = 0; i < length; i++) {
    mqtt_mqtt_sub_value += (char)payload[i];
  }
}
void mqtt_mqtt_sub_ensure_connected() {
  if (WiFi.status() != WL_CONNECTED) {
    return; // WiFi not up yet; retry on the next loop tick
  }
  if (!mqtt_mqtt_sub_client.connected()) {
    mqtt_mqtt_sub_client.setServer(mqtt_mqtt_sub_broker, mqtt_mqtt_sub_port);
    if (mqtt_mqtt_sub_client.connect(mqtt_mqtt_sub_client_id)) {
      mqtt_mqtt_sub_client.subscribe(mqtt_mqtt_sub_topic);
    }
  }
}

void setup() {
  // --- Setup ---
  // --- WiFi connect (Cloud Nodes) ---
  WiFi.mode(WIFI_STA);
  WiFi.begin(wifi_ssid, wifi_password);
  while (WiFi.status() != WL_CONNECTED) {
    yield();
  }
  figma_figma_1_client.setServer(figma_figma_1_broker, figma_figma_1_port);
  figma_figma_1_client.setCallback(figma_figma_1_on_message);
  figma_figma_1_ensure_connected();
  // Llm Node llm_1: request issued from loop() once connected
  monitor_monitor_1_client.setServer(monitor_monitor_1_broker, monitor_monitor_1_port);
  monitor_monitor_1_ensure_connected();
  mqtt_mqtt_pub_client.setServer(mqtt_mqtt_pub_broker, mqtt_mqtt_pub_port);
  mqtt_mqtt_pub_ensure_connected();
  mqtt_mqtt_sub_client.setServer(mqtt_mqtt_sub_broker, mqtt_mqtt_sub_port);
  mqtt_mqtt_sub_client.setCallback(mqtt_mqtt_sub_on_message);
  mqtt_mqtt_sub_ensure_connected();
}

void loop() {
  static unsigned long previousMillis = 0;
  const unsigned long interval = 1; // ms; non-blocking scheduler tick
  unsigned long currentMillis = millis();
  if (currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;
    // --- Scheduled tasks ---
    figma_figma_1_ensure_connected();
    figma_figma_1_client.loop();
    // Figma Node figma_1 has no wired input — subscribe-only, nothing to publish
    double llm_llm_1_trigger_now0 = ((double)(figma_figma_1_value.toFloat()));
    bool llm_llm_1_trigger_fired0 = (llm_llm_1_trigger_now0 != llm_llm_1_trigger_prev0);
    llm_llm_1_trigger_prev0 = llm_llm_1_trigger_now0;
    if ((llm_llm_1_trigger_fired0)) {
      llm_llm_1_request();
    }
    mqtt_mqtt_pub_ensure_connected();
    mqtt_mqtt_pub_client.loop();
    String mqtt_mqtt_pub_trigger_now0 = (llm_llm_1_value);
    bool mqtt_mqtt_pub_trigger_fired0 = (mqtt_mqtt_pub_trigger_now0 != mqtt_mqtt_pub_trigger_prev0);
    mqtt_mqtt_pub_trigger_prev0 = mqtt_mqtt_pub_trigger_now0;
    if (mqtt_mqtt_pub_trigger_fired0 && mqtt_mqtt_pub_client.connected()) {
      mqtt_mqtt_pub_client.publish(mqtt_mqtt_pub_topic, ((llm_llm_1_value)).c_str());
    }
    mqtt_mqtt_sub_ensure_connected();
    mqtt_mqtt_sub_client.loop();
    monitor_monitor_1_ensure_connected();
    monitor_monitor_1_client.loop();
    if (monitor_monitor_1_client.connected()) {
      String monitor_monitor_1_next = String(mqtt_mqtt_sub_value.toFloat());
      if (monitor_monitor_1_next != monitor_monitor_1_last_published) {
        monitor_monitor_1_client.publish(monitor_monitor_1_topic, monitor_monitor_1_next.c_str());
        monitor_monitor_1_last_published = monitor_monitor_1_next;
      }
    }
  }
}
