// Generated by microflow v0.12.0.
// Target board: Arduino Uno (uno).
// Sketch skeleton for 4 node(s).

// --- Declarations ---
// node led-1 (Led)
const uint8_t led_led_1_pin = 11;
bool led_led_1_on = false;
// node map-1 (RangeMap)
double range_map_map_1_value = 0.0;
// node sensor-1 (Sensor)
const uint8_t sensor_sensor_1_pin = 15; // A1
int sensor_sensor_1_value = 0;
// node smooth-1 (Smooth)
double smooth_smooth_1_value = 0.0;
bool smooth_smooth_1_value_seeded = false;

void setup() {
  // --- Setup ---
  pinMode(led_led_1_pin, OUTPUT);
  digitalWrite(led_led_1_pin, LOW);
  pinMode(sensor_sensor_1_pin, INPUT);
}

void loop() {
  static unsigned long previousMillis = 0;
  const unsigned long interval = 1; // ms; non-blocking scheduler tick
  unsigned long currentMillis = millis();
  if (currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;
    // --- Scheduled tasks ---
    sensor_sensor_1_value = analogRead(sensor_sensor_1_pin);
    range_map_map_1_value = round((((((double)(sensor_sensor_1_value)) - 0.0) * (255.0 - 0.0) / (1023.0 - 0.0) + 0.0)) * 1.0) / 1.0;
    if (!smooth_smooth_1_value_seeded) { smooth_smooth_1_value = ((double)(range_map_map_1_value)); smooth_smooth_1_value_seeded = true; } else { smooth_smooth_1_value = (1.0 - 0.5) * ((double)(range_map_map_1_value)) + 0.5 * smooth_smooth_1_value; }
    uint8_t led_led_1_brightness = (uint8_t)constrain((double)(smooth_smooth_1_value), 0.0, 255.0);
    analogWrite(led_led_1_pin, led_led_1_brightness);
    led_led_1_on = led_led_1_brightness > 0;
  }
}
