// Generated by microflow v0.12.0.
// Target board: Arduino Uno (uno).
// Sketch skeleton for 2 node(s).

// --- Includes ---
// Libraries not bundled with your board's core must be installed first:
// Arduino IDE > Sketch > Include Library > Manage Libraries…
#include <MIDI.h>

// --- Declarations ---
// shared across nodes (deduplicated)
MIDI_CREATE_DEFAULT_INSTANCE();
byte midi_rx_type = 0;
byte midi_rx_channel = 0;
byte midi_rx_data1 = 0;
byte midi_rx_data2 = 0;
bool midi_rx_fresh = false;
void midi_pump() {
  midi_rx_fresh = MIDI.read();
  if (midi_rx_fresh) {
    midi_rx_type = (byte)MIDI.getType();
    midi_rx_channel = (byte)MIDI.getChannel();
    midi_rx_data1 = (byte)MIDI.getData1();
    midi_rx_data2 = (byte)MIDI.getData2();
  }
}
// node midi-in (Midi)
byte midi_midi_in_value = 0;
// node midi-out (Midi)
double midi_midi_out_send_prev0 = 0.0;

void setup() {
  // --- Setup ---
  MIDI.begin(MIDI_CHANNEL_OMNI);
  MIDI.turnThruOff();
}

void loop() {
  static unsigned long previousMillis = 0;
  const unsigned long interval = 1; // ms; non-blocking scheduler tick
  unsigned long currentMillis = millis();
  if (currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;
    // --- Scheduled tasks ---
    midi_pump();
    if (midi_rx_fresh && midi_rx_type == 0xB0 && midi_rx_data1 == 1) {
      midi_midi_in_value = midi_rx_data2;
    }
    double midi_midi_out_send_now0 = ((double)((double)midi_midi_in_value));
    bool midi_midi_out_send_fired0 = (midi_midi_out_send_now0 != midi_midi_out_send_prev0);
    midi_midi_out_send_prev0 = midi_midi_out_send_now0;
    if (midi_midi_out_send_fired0) { if ((((double)midi_midi_in_value) != 0.0)) { MIDI.sendNoteOn(60, 127, 1); } else { MIDI.sendNoteOff(60, 0, 1); } }
  }
}
