// Generated by microflow v0.12.0.
// Target board: Arduino Uno (uno).
// Sketch skeleton for 2 node(s).

// --- Includes ---
// Libraries not bundled with your board's core must be installed first:
// Arduino IDE > Sketch > Include Library > Manage Libraries…
#include <Adafruit_NeoPixel.h>

// --- Declarations ---
// node osc-1 (Oscillator)
unsigned long oscillator_osc_1_start = 0;
double oscillator_osc_1_value = 0.0;
bool oscillator_osc_1_running = true;
// node pixel-1 (Pixel)
Adafruit_NeoPixel pixel_pixel_1(8, 6, NEO_GRB + NEO_KHZ800);
const uint32_t pixel_pixel_1_presets[2][2] = {
  {0xFF0000, 0x00FF00},
  {0x0000FF, 0xFFFFFF}
};
const uint16_t pixel_pixel_1_preset_len[2] = {2, 2};
double pixel_pixel_1_value_prev0 = 0.0;

void setup() {
  // --- Setup ---
  oscillator_osc_1_start = millis();
  pixel_pixel_1.begin();
  pixel_pixel_1.clear();
  pixel_pixel_1.show();
}

void loop() {
  static unsigned long previousMillis = 0;
  const unsigned long interval = 1; // ms; non-blocking scheduler tick
  unsigned long currentMillis = millis();
  if (currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;
    // --- Scheduled tasks ---
    if (oscillator_osc_1_running) {
      double oscillator_osc_1_t = (double)(millis() - oscillator_osc_1_start) + 0.0;
      oscillator_osc_1_value = 1.0 * sin(oscillator_osc_1_t * (2.0 * PI / 2000.0)) + 0.0;
    }
    double pixel_pixel_1_value_now0 = ((double)(oscillator_osc_1_value));
    bool pixel_pixel_1_value_fired0 = (pixel_pixel_1_value_now0 != pixel_pixel_1_value_prev0);
    pixel_pixel_1_value_prev0 = pixel_pixel_1_value_now0;
    if (pixel_pixel_1_value_fired0) {
      uint16_t pixel_pixel_1_idx = (uint16_t)constrain(round(((double)(oscillator_osc_1_value))), 0.0, 1.0);
      for (uint16_t pixel_pixel_1_i = 0; pixel_pixel_1_i < pixel_pixel_1_preset_len[pixel_pixel_1_idx]; pixel_pixel_1_i++) { pixel_pixel_1.setPixelColor(pixel_pixel_1_i, pixel_pixel_1_presets[pixel_pixel_1_idx][pixel_pixel_1_i]); }
      pixel_pixel_1.show();
    }
  }
}
