// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A capability a board may offer, against which a Node can declare a
 * requirement. Membership is the check: a board satisfies a requirement iff
 * the capability is present in its [`BoardTarget::capabilities`] set.
 */
export type BoardCapability = "networking";
