// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinInfo } from "./PinInfo";

/**
 * Board state for frontend events
 */
export type BoardState = { "state": "connected", port: string, firmwareName: string, firmwareVersion: string, pins: Array<PinInfo>, } | { "state": "connecting", } | { "state": "flashing", port: string, board: string, } | { "state": "disconnected", } | { "state": "error", error: string | null, };
