// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One logical pin in a board's pin map.
 *
 * `number` is how the pin is addressed in the generated Sketch (the value an
 * emitter writes into `pinMode`/`digitalWrite`). `pwm` and `analog_input`
 * record the pin's hardware abilities so a target can answer which pins drive
 * PWM and which are analog inputs without per-board code branches.
 */
export type BoardPin = { 
/**
 * The pin number as addressed in the generated Sketch.
 */
number: number, 
/**
 * Whether this pin supports PWM output (`analogWrite`).
 */
pwm: boolean, 
/**
 * Whether this pin is an analog input.
 */
analogInput: boolean, };
