// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardCapability } from "./BoardCapability";
import type { BoardPin } from "./BoardPin";

/**
 * A supported board target: the consistency boundary for one board's pin and
 * capability facts.
 */
export type BoardTarget = { 
/**
 * Stable identifier, aligned with the flasher's lowercase board ids where
 * they overlap (e.g. `uno`, `nano`, `esp32`).
 */
id: string, 
/**
 * Human-readable name presented to the Flow Author (e.g. `Arduino Uno`).
 */
name: string, 
/**
 * The board's pin map.
 */
pins: Array<BoardPin>, 
/**
 * Available hardware timers, by name (e.g. `Timer0`).
 */
timers: Array<string>, 
/**
 * Capabilities this board offers.
 */
capabilities: Array<BoardCapability>, };
