// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UI-facing bring-up phase. Hosts map this onto their `BoardState` payload
 * (the desktop fills in port/pins/firmware from its probe result).
 */
export type BringUpPhase = { "kind": "disconnected" } | { "kind": "connecting" } | { "kind": "flashing", board: string, } | { "kind": "connected" } | { "kind": "error", detail: string, };
