// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened in the host, fed into [`BringUp::handle`].
 */
export type BringUpEvent = { "type": "portReady", board: string | null, autoFlash: boolean, explicit: boolean, } | { "type": "probeOk" } | { "type": "probeFailed" } | { "type": "flashProgress", done: number, total: number, } | { "type": "flashOk" } | { "type": "flashFailed", detail: string, } | { "type": "connectionLost" } | { "type": "portGone" } | { "type": "disconnectRequested" };
