// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BringUpPhase } from "./BringUpPhase";

/**
 * What the host must do next, in order.
 */
export type BringUpAction = { "type": "probe", afterFlash: boolean, } | { "type": "flash", board: string, } | { "type": "closePort" } | { "type": "scheduleRetry" } | { "type": "notify", phase: BringUpPhase, } | { "type": "notifyFlashProgress", percent: number, };
