// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionStatus } from "./ConnectionStatus";

/**
 * Broker status info returned to frontend
 */
export type BrokerStatus = { id: string, status: ConnectionStatus, };
