// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An outbound cloud call a node asked the host to perform (ADR-0009): the
 * sans-IO replacement for the old in-component `tokio::spawn`. A cloud node's
 * `dispatch` records one of these via [`RuntimeContext::request_cloud`] instead
 * of touching the network; the host's [`EffectsSink::perform_cloud`] performs
 * it, and any result re-enters through `FlowRuntime::inject_event` on `source`.
 * `source` (the node id) is the correlation key for that re-entry.
 */
export type CloudRequest = { 
/**
 * The node that issued the request; results re-enter via `inject_event`
 * targeting this id.
 */
source: string, } & ({ "kind": "mqttPublish", brokerId: string, topic: string, payload: Array<number>, retain: boolean, } | { "kind": "llmGenerate", providerId: string, model: string, system: string | null, prompt: string, } | { "kind": "midiSend", deviceName: string, bytes: Array<number>, } | { "kind": "audioPlay", 
/**
 * Which record to play: an index into the node's `data.tracks`.
 */
track: number, 
/**
 * 0.0-1.0, already clamped by the node.
 */
volume: number, loop: boolean, } | { "kind": "audioStop" });
