// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of cloud I/O a [`CloudRequest`] is. Carries only plain data (no
 * service handles, no Tokio) so a cloud node stays fully sans-IO and unit-
 * testable by asserting the emitted request. The host maps each variant onto
 * its platform transport (desktop `rumqttc`/`reqwest`; browser WSS/`fetch`).
 */
export type CloudRequestKind = { "kind": "mqttPublish", brokerId: string, topic: string, payload: Array<number>, retain: boolean, } | { "kind": "llmGenerate", providerId: string, model: string, system: string | null, prompt: string, } | { "kind": "midiSend", deviceName: string, bytes: Array<number>, };
