// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentValue } from "./ComponentValue";

/**
 * Event emitted by a component.
 *
 * `Serialize`-only: the frontend consumes these (via the desktop
 * `component-event` Tauri event, or the browser reactor's `Effects`), never
 * sends them back. `Arc<str>` fields stay cheap to clone during fanout.
 */
export type ComponentEvent = { source: string, sourceHandle: string, value: ComponentValue, edgeId: string | null, 
/**
 * Flow version when the event was created (stale-gating).
 */
sequence: number, };
