// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Value that a component can hold
 */
export type ComponentValue = boolean | number | string | { r: number, g: number, b: number, a: number, } | Array<ComponentValue>;
