// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentValue } from "./ComponentValue";

/**
 * Event emitted by a component.
 *
 * `Serialize`-only: the frontend consumes these via the `component-event`
 * Tauri event, never sends them back. Dropping `Deserialize` lets us keep
 * `Arc<str>` fields without a custom deserializer (which `ts-rs` cannot
 * parse and would otherwise warn about on every build).
 */
export type ComponentEvent = { source: string, sourceHandle: string, value: ComponentValue, edgeId: string | null, sequence: number, };
