// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Arduino core family a board compiles against. Some libraries differ per
 * core (the AVR `Servo.h` does not build on the ESP32 core, which uses
 * `ESP32Servo.h` instead), so emitters that pull in such a library consult
 * this fact.
 */
export type CoreFamily = "avr" | "esp32";
