// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubKind } from "./SubKind";

/**
 * One reconciled subscription: exactly one per `(broker_id, topic)`. Carries the
 * winning node id + kind so a host can tell when a topic's *owner* changed (and
 * must be re-subscribed) versus left untouched. Serializes to the
 * `{ brokerId, topic, nodeId, kind }` shape the browser host consumes via the
 * wasm `reconcileSubscriptions()` binding.
 */
export type DesiredSub = { brokerId: string, topic: string, nodeId: string, kind: SubKind, };
