// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity of a [`NodeDiagnostic`], mapped 1:1 onto the UI's existing per-node
 * `error` (red) / `warning` (amber) badge on `NodeContainer`.
 */
export type DiagnosticLevel = "warning" | "error";
