// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudRequest } from "./CloudRequest";
import type { ComponentEvent } from "./ComponentEvent";
import type { NodeDiagnostic } from "./NodeDiagnostic";
import type { Wakeup } from "./Wakeup";

/**
 * Everything the host must do after one runtime turn. Bytes go to the serial
 * port, events to the UI stores, wakeups to host timers, cancellations clear
 * timers that are no longer wanted, cloud requests go to the network, node
 * diagnostics go to the node's badge in the UI.
 */
export type Effects = { outboundBytes: Array<number>, componentEvents: Array<ComponentEvent>, wakeups: Array<Wakeup>, cancellations: Array<number>, cloudRequests: Array<CloudRequest>, nodeDiagnostics: Array<NodeDiagnostic>, };
