// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What changed after feeding a chunk of incoming bytes. Returned as JSON from
 * [`FirmataSession::feed`].
 */
export type FeedResult = { pinChanges: Array<{ pin: number, value: number, isAnalog: boolean, }>, i2cReplies: Array<{ address: number, register: number, data: Array<number>, }>, 
/**
 * A firmware report arrived this feed — the caller should re-read
 * `firmwareName` / `firmwareVersion`.
 */
firmwareUpdated: boolean, 
/**
 * A capability or analog-mapping response arrived — re-read `pinsJson`.
 */
capabilitiesUpdated: boolean, };
