// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Figma plugin-handshake publish a host must make over MQTT when the set of
 * live Figma plugin uids changes. The handshake **protocol** — topic shape,
 * payloads, retain flags — lives here once; the host owns only the publish I/O.
 * Previously this lived in two languages (browser `flow-reactor.ts`
 * `figmaLifecycle`, desktop `flow_update` tail), kept in lockstep by a comment.
 * Serializes to `{ brokerId, topic, payload, retain }` for the browser host
 * (via the wasm `figmaAnnounceActions` binding); the desktop host consumes the
 * struct directly. See [`figma_announce_actions`].
 */
export type FigmaPublish = { brokerId: string, topic: string, payload: string, retain: boolean, };
