// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One action the executor must perform on the serial transport.
 *
 * `rename_all` camelCases the variant tags (`reset`, `setBaud`, …); the
 * separate `rename_all_fields` is essential — it camelCases the *fields inside*
 * the struct variants (`delay_ms` → `delayMs`, `read_len` → `readLen`, …). Without
 * it those multi-word fields serialize `snake_case` and arrive `undefined` in the
 * JS executor (which reads `delayMs`/`readLen`/`timeoutMs`/`waitMs`).
 */
export type FlashStep = { "kind": "reset", dtr: boolean, rts: boolean, delayMs: number, } | { "kind": "setBaud", baud: number, } | { "kind": "flushInput" } | { "kind": "transact", write: Array<number>, readLen: number, timeoutMs: number, } | { "kind": "delay", ms: number, } | { "kind": "reacquirePort", waitMs: number, baud: number, } | { "kind": "progress", done: number, total: number, } | { "kind": "done" } | { "kind": "error", message: string, };
