// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowEdge } from "./FlowEdge";
import type { FlowNode } from "./FlowNode";

/**
 * Flow update message from frontend
 */
export type FlowUpdate = { nodes: Array<FlowNode>, edges: Array<FlowEdge>, };
