// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An edge connecting two nodes
 */
export type FlowEdge = { id: string | null, source: string, target: string, sourceHandle: string, targetHandle: string, };
