// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

/**
 * A node in the flow graph
 */
export type FlowNode = { id: string, type: string | null, data: Record<string, unknown>, position: Position, };
