// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationProblem } from "./ValidationProblem";

/**
 * The outcome of generating a Sketch for a selected board target.
 *
 * Generation either emits a runnable `.ino` source, or — when the Flow cannot
 * run on the selected target — surfaces the validation problems that prevented
 * emission. This enforces the invariant that **no unrunnable code is ever
 * emitted**: when problems exist, no `sketch` is produced.
 */
export type GenerationOutcome = { "sketch": string } | { "problems": Array<ValidationProblem> };
