// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationProblem } from "./ValidationProblem";

/**
 * The outcome of generating a Sketch for a selected board target.
 *
 * Generation always emits the `.ino` source unless a problem of
 * [`validate::ProblemSeverity::Error`] severity exists — those mean the
 * emitted C++ itself would not compile (e.g. two Node ids sanitizing to the
 * same identifier). Board-fit conflicts (missing pin, missing networking, …)
 * are [`validate::ProblemSeverity::Warning`]s: the Sketch is still emitted and
 * the warnings ride alongside it, so the Author decides whether they apply to
 * their actual hardware.
 */
export type GenerationOutcome = { 
/**
 * The generated `.ino` source; `None` only when `problems` contains at
 * least one error-severity problem.
 */
sketch: string | null, 
/**
 * The validation problems (each naming a Node, the constraint it
 * violates, and its severity). Empty when the Flow fits the target.
 */
problems: Array<ValidationProblem>, };
