// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One MIDI listener a host must feed: route every message from ports whose
 * name contains `device_name` (case-insensitive; "" = every port) to `node_id`
 * via `deliver_message`. No reconcile/winner-selection on purpose — several
 * nodes listening to one device ALL receive its messages (unlike a broker
 * topic, which keeps exactly one callback). Serializes to the
 * `{ nodeId, deviceName }` shape the browser host consumes via the wasm
 * `midiListeners()` binding.
 */
export type MidiListener = { nodeId: string, deviceName: string, };
