// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One required-but-missing credential, naming the field the Author left empty
 * and a human-readable reason. Surfaced to the Author so they know *which*
 * credential to supply rather than getting a silently non-connecting Sketch.
 */
export type MissingCredential = {
  /**
   * The credentials field that is required but empty (e.g. `wifiSsid`). Names
   * the JSON field of [`Credentials`] so the surface can highlight it.
   */
  field: string;
  /**
   * Human-readable reason the credential is required for this Flow.
   */
  reason: string;
};
