// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload of the `mqtt-message` Tauri event. Frontend deserializes this with
 * `snake_case` field names; do not hand-roll JSON for this event elsewhere.
 */
export type MqttMessage = { broker_id: string, topic: string, payload: string, 
/**
 * Set when the message reached a subscribed component (Plain/TopicAware
 * flows in `runtime::commands`); `null` for direct broker subscriptions.
 * Always serialized so the ts-rs binding mirrors the struct verbatim.
 */
component_id: string | null, };
