// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticLevel } from "./DiagnosticLevel";

/**
 * A runtime health signal a node raises about *itself* — surfaced on the node
 * in the UI (not routed across edges like a [`ComponentEvent`]). A hardware
 * node uses this to report a fault it can only see at runtime, e.g. an I2C
 * device whose reads never ACK ("too few bytes"). `message: None` clears any
 * prior diagnostic on that node (recovery). Nodes should raise these only on a
 * state *transition* so a per-poll failure doesn't spam the channel.
 */
export type NodeDiagnostic = { 
/**
 * The node the diagnostic is about (and displayed on).
 */
node: string, level: DiagnosticLevel, 
/**
 * The message to show; `None` clears the node's diagnostic.
 */
message: string | null, };
