// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pin information matching frontend Pin type
 */
export type PinInfo = { pin: number, supportedModes: Array<number>, analogChannel: number, };
