// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How severe a [`ValidationProblem`] is: whether it blocks emission.
 */
export type ProblemSeverity = "error" | "warning";
