// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SerialPortInfo } from "./SerialPortInfo";

/**
 * Event payload for serial port connection/disconnection
 */
export type SerialPortEvent = { port: SerialPortInfo, event_type: string, };
