// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a serial port
 */
export type SerialPortInfo = { port_name: string, port_type: string, description: string | null, has_firmata: boolean | null, vid: number | null, pid: number | null, };
