// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which callback shape a subscription drives — the routing identity a broker's
 * single per-topic callback carries. Serializes to the `plain`/`topicAware`/
 * `displayEcho` strings both hosts use on the wire.
 */
export type SubKind = "plain" | "topicAware" | "displayEcho";
