// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemSeverity } from "./ProblemSeverity";

/**
 * One way a Flow conflicts with the selected board target (or with emission
 * itself — see [`ProblemSeverity`]).
 *
 * Carries the offending Node's id and type plus a human-readable `message`
 * naming the Node and the constraint, so the frontend can present an
 * actionable message alongside (or, for errors, instead of) the Sketch.
 */
export type ValidationProblem = { 
/**
 * The Flow id of the Node that violates a constraint.
 */
nodeId: string, 
/**
 * The Node's type (e.g. `Led`, `Mqtt`), or `unknown` when typeless.
 */
nodeType: string, 
/**
 * Human-readable description naming the Node and the constraint.
 */
message: string, 
/**
 * Whether this problem blocks emission.
 */
severity: ProblemSeverity, };
