// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One reason a Flow cannot be generated for the selected board target.
 *
 * Carries the offending Node's id and type plus a human-readable `message`
 * naming the Node and the constraint, so the frontend can present an
 * actionable validation error instead of unrunnable code.
 */
export type ValidationProblem = { 
/**
 * The Flow id of the Node that violates a constraint.
 */
nodeId: string, 
/**
 * The Node's type (e.g. `Led`, `Mqtt`), or `unknown` when typeless.
 */
nodeType: string, 
/**
 * Human-readable description naming the Node and the constraint.
 */
message: string, };
