// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A future self-callback a timer node asked for. The host arms a timer for
 * `delay_ms`; when it fires it calls `FlowRuntime::wake(node_id, method)`.
 */
export type Wakeup = { id: number, nodeId: string, method: string, delayMs: number, };
