import type { Template } from "../types";
import { ledData, intervalData, counterData, compareNumberData } from "../data-factories";

export const trafficLight: Template = {
  id: "traffic-light",
  name: "Traffic Light",
  description:
    "Build a simple traffic light that cycles through red, yellow, and green LEDs.",
  difficulty: "beginner",
  categories: ["LEDs", "Fun", "Animation"],
  nodes: [
    {
      id: "interval-1",
      type: "Interval",
      position: { x: 100, y: 250 },
      data: { ...intervalData(2000), label: "Cycle Timer" },
    },
    {
      id: "counter-1",
      type: "Counter",
      position: { x: 400, y: 250 },
      data: { ...counterData(), label: "State" },
    },
    {
      id: "compare-red",
      type: "Compare",
      position: { x: 700, y: 100 },
      data: { ...compareNumberData("equals", 0), label: "Is Red?" },
    },
    {
      id: "compare-yellow",
      type: "Compare",
      position: { x: 700, y: 250 },
      data: { ...compareNumberData("equals", 1), label: "Is Yellow?" },
    },
    {
      id: "compare-green",
      type: "Compare",
      position: { x: 700, y: 400 },
      data: { ...compareNumberData("equals", 2), label: "Is Green?" },
    },
    {
      id: "led-red",
      type: "Led",
      position: { x: 1000, y: 100 },
      data: { ...ledData(11), label: "Red" },
    },
    {
      id: "led-yellow",
      type: "Led",
      position: { x: 1000, y: 250 },
      data: { ...ledData(10), label: "Yellow" },
    },
    {
      id: "led-green",
      type: "Led",
      position: { x: 1000, y: 400 },
      data: { ...ledData(9), label: "Green" },
    },
  ],
  edges: [
    {
      id: "e-interval-counter",
      source: "interval-1",
      target: "counter-1",
      sourceHandle: "change",
      targetHandle: "increment",
      type: "animated",
    },
    {
      id: "e-counter-red",
      source: "counter-1",
      target: "compare-red",
      sourceHandle: "change",
      targetHandle: "check",
      type: "animated",
    },
    {
      id: "e-counter-yellow",
      source: "counter-1",
      target: "compare-yellow",
      sourceHandle: "change",
      targetHandle: "check",
      type: "animated",
    },
    {
      id: "e-counter-green",
      source: "counter-1",
      target: "compare-green",
      sourceHandle: "change",
      targetHandle: "check",
      type: "animated",
    },
    {
      id: "e-red-on",
      source: "compare-red",
      target: "led-red",
      sourceHandle: "true",
      targetHandle: "turnOn",
      type: "animated",
    },
    {
      id: "e-red-off",
      source: "compare-red",
      target: "led-red",
      sourceHandle: "false",
      targetHandle: "turnOff",
      type: "animated",
    },
    {
      id: "e-yellow-on",
      source: "compare-yellow",
      target: "led-yellow",
      sourceHandle: "true",
      targetHandle: "turnOn",
      type: "animated",
    },
    {
      id: "e-yellow-off",
      source: "compare-yellow",
      target: "led-yellow",
      sourceHandle: "false",
      targetHandle: "turnOff",
      type: "animated",
    },
    {
      id: "e-green-on",
      source: "compare-green",
      target: "led-green",
      sourceHandle: "true",
      targetHandle: "turnOn",
      type: "animated",
    },
    {
      id: "e-green-off",
      source: "compare-green",
      target: "led-green",
      sourceHandle: "false",
      targetHandle: "turnOff",
      type: "animated",
    },
  ],
};
