use std::collections::HashMap;
use std::fmt::Write;
use std::fs;
use std::path::Path;

fn main() {
    tauri_build::build();

    let manifest_path = "../node-components.json";
    println!("cargo:rerun-if-changed={manifest_path}");

    let content = fs::read_to_string(manifest_path)
        .expect("Failed to read node-components.json");
    let json: serde_json::Value = serde_json::from_str(&content)
        .expect("Failed to parse node-components.json");

    let entries = json["entries"].as_array()
        .expect("entries must be an array");
    let impls = json["impls"].as_array()
        .expect("impls must be an array");

    // Build impl lookup: name -> (category, requires_hardware, ports_literal).
    // `requiresHardware` is load-bearing: it picks `register_hardware::<T>`
    // (which adds a `HardwareComponent` bound) over `register::<T>`. A catalog
    // entry marked `requiresHardware: true` whose impl forgot `HardwareComponent`
    // fails to compile.
    // `ports` is the catalog declaration of the impl's **Port** set; emitted
    // here as a Rust slice literal and asserted equal to `B::ports()` inside
    // the registry. See `CONTEXT.md` § Port and ADR-0001.
    let mut impl_meta: HashMap<&str, (&str, bool, String)> = HashMap::new();
    for i in impls {
        let name = i["name"].as_str().expect("impl.name");
        let category = i["category"].as_str().expect("impl.category");
        let requires_hardware = i["requiresHardware"].as_bool().expect("impl.requiresHardware");
        let ports = i["ports"].as_array()
            .unwrap_or_else(|| panic!("impl {name:?} missing 'ports' array"));
        let mut ports_lit = String::from("&[");
        for (idx, p) in ports.iter().enumerate() {
            let s = p.as_str()
                .unwrap_or_else(|| panic!("impl {name:?}: every port must be a string"));
            if idx > 0 { ports_lit.push_str(", "); }
            write!(ports_lit, "\"{s}\"").unwrap();
        }
        ports_lit.push(']');
        impl_meta.insert(name, (category, requires_hardware, ports_lit));
    }

    // Validate: every entry's impl exists in impls
    for e in entries {
        let entry_name = e["name"].as_str().expect("entry.name");
        let impl_name = e["impl"].as_str().expect("entry.impl");
        assert!(
            impl_meta.contains_key(impl_name),
            "entry {entry_name:?} references unknown impl {impl_name:?}"
        );
    }

    // Body is included into ComponentRegistry::register_all, so it must be
    // valid as a sequence of statements. No `use` items — emit fully
    // qualified `super::<category>::<Impl>` paths inline.
    // Wrap in `{ ... }` so the result is a single block expression suitable
    // for include! at expression position inside ComponentRegistry::register_all.
    let mut body = String::new();
    body.push_str("// GENERATED by build.rs from node-components.json — do not edit\n");
    body.push_str("{\n");

    for e in entries {
        let entry_name = e["name"].as_str().unwrap();
        let impl_name = e["impl"].as_str().unwrap();
        let (category, requires_hardware, ports_lit) = &impl_meta[impl_name];
        let helper = if *requires_hardware { "register_hardware" } else { "register" };
        writeln!(
            body,
            "    self.{helper}::<super::{category}::{impl_name}>(\"{entry_name}\", {ports_lit});"
        ).unwrap();
    }

    body.push_str("}\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("register_all_body.rs"), body)
        .expect("Failed to write register_all_body.rs");
}
