use std::collections::HashMap;
use std::fmt::Write;
use std::fs;
use std::path::Path;

fn main() {
    tauri_build::build();

    let manifest_path = "../node-components.json";
    println!("cargo:rerun-if-changed={manifest_path}");

    let content = fs::read_to_string(manifest_path)
        .expect("Failed to read node-components.json");
    let json: serde_json::Value = serde_json::from_str(&content)
        .expect("Failed to parse node-components.json");

    let entries = json["entries"].as_array()
        .expect("entries must be an array");
    let impls = json["impls"].as_array()
        .expect("impls must be an array");

    // Build impl lookup: name -> (category, uses_runtime_context).
    // The `requiresHardware` flag is validated for presence (frontend codegen + UI consume it)
    // but is not consumed by the Rust registry — the runtime always calls `initialize`,
    // and software components default to a no-op.
    let mut impl_meta: HashMap<&str, (&str, bool)> = HashMap::new();
    for i in impls {
        let name = i["name"].as_str().expect("impl.name");
        let category = i["category"].as_str().expect("impl.category");
        let _ = i["requiresHardware"].as_bool().expect("impl.requiresHardware");
        let uses_runtime_context = i["usesRuntimeContext"].as_bool().unwrap_or(false);
        impl_meta.insert(name, (category, uses_runtime_context));
    }

    // Validate: every entry's impl exists in impls
    for e in entries {
        let entry_name = e["name"].as_str().expect("entry.name");
        let impl_name = e["impl"].as_str().expect("entry.impl");
        assert!(
            impl_meta.contains_key(impl_name),
            "entry {entry_name:?} references unknown impl {impl_name:?}"
        );
    }

    // Body is included into ComponentRegistry::register_all, so it must be
    // valid as a sequence of statements. No `use` items — emit fully
    // qualified `super::<category>::<Impl>` paths inline.
    // Wrap in `{ ... }` so the result is a single block expression suitable
    // for include! at expression position inside ComponentRegistry::register_all.
    let mut body = String::new();
    body.push_str("// GENERATED by build.rs from node-components.json — do not edit\n");
    body.push_str("{\n");

    for e in entries {
        let entry_name = e["name"].as_str().unwrap();
        let impl_name = e["impl"].as_str().unwrap();
        let (category, uses_runtime_context) = impl_meta[impl_name];
        if uses_runtime_context {
            // Component opts in to RuntimeContext via a custom from_data() factory.
            writeln!(
                body,
                "    self.register(\"{entry_name}\", |id, data, ctx| super::{category}::{impl_name}::from_data(id, data, ctx));"
            ).unwrap();
        } else {
            writeln!(
                body,
                "    self.register(\"{entry_name}\", |id, data, _ctx| Box::new(super::{category}::{impl_name}::new(id, parse_config::<super::{category}::{impl_name}Config>(data))));"
            ).unwrap();
        }
    }

    body.push_str("}\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("register_all_body.rs"), body)
        .expect("Failed to write register_all_body.rs");
}
