// Browser code generation, backed by the same Rust generator the desktop app
// runs natively — compiled to WebAssembly in the `microflow-codegen-wasm` crate
// (single source of truth, no logic duplicated in TS). The `.wasm` and its JS
// glue are generated by `wasm-pack` into ./generated (a build artifact; run
// `bun run build:wasm` — see apps/web/package.json). The boundary is JSON in /
// JSON out, mirroring the desktop Tauri IPC boundary exactly.

import type { Edge, Node } from "@xyflow/react";
import type { Credentials } from "@/lib/bindings/Credentials";
import type { GenerationOutcome } from "@/lib/bindings/GenerationOutcome";
import type { MissingCredential } from "@/lib/bindings/MissingCredential";

import init, {
  check_credentials as wasmCheckCredentials,
  generate_sketch as wasmGenerateSketch,
} from "./generated/microflow_codegen_wasm.js";
// `?url` asks Vite to emit the wasm as a hashed asset and hand us its URL, so
// the module loads correctly in dev and after a production build without any
// extra Vite plugin.
import wasmUrl from "./generated/microflow_codegen_wasm_bg.wasm?url";

/**
 * Lazily instantiate the wasm module exactly once. Every entry point awaits this
 * first; concurrent callers share the single in-flight promise so the module is
 * fetched and compiled only one time.
 */
let initPromise: Promise<unknown> | null = null;
function ensureReady(): Promise<unknown> {
  if (initPromise === null) {
    initPromise = init({ module_or_path: wasmUrl });
  }
  return initPromise;
}

/** Serialize the optional credentials to JSON, or `undefined` to pass through. */
function serializeCredentials(credentials?: Credentials): string | undefined {
  return credentials === undefined ? undefined : JSON.stringify(credentials);
}

/**
 * Generate the Arduino sketch in the browser for the given Flow graph and
 * selected board target. Returns the parsed {@link GenerationOutcome} — either
 * the `.ino` source or the validation problems that prevented emission.
 *
 * `targetId` omitted ⇒ the generator defaults to the Uno, identical to desktop.
 */
export async function generateSketch(
  flow: { nodes: Node[]; edges: Edge[] },
  targetId?: string,
  credentials?: Credentials,
): Promise<GenerationOutcome> {
  await ensureReady();
  const json = wasmGenerateSketch(
    JSON.stringify(flow),
    targetId,
    serializeCredentials(credentials),
  );
  return JSON.parse(json) as GenerationOutcome;
}

/**
 * Report which required network credentials are missing for a Flow on the
 * selected target, in the browser. Empty array when nothing is required (no
 * Cloud Nodes, or a non-networking target).
 */
export async function checkCredentials(
  flow: { nodes: Node[]; edges: Edge[] },
  targetId?: string,
  credentials?: Credentials,
): Promise<MissingCredential[]> {
  await ensureReady();
  const json = wasmCheckCredentials(
    JSON.stringify(flow),
    targetId,
    serializeCredentials(credentials),
  );
  return JSON.parse(json) as MissingCredential[];
}
