//! Sketch Generation context — translate a Flow graph ahead-of-time into an
//! Arduino sketch (`.ino` source).
//!
//! This module is the entry point of the Sketch Generation context. It sits as
//! a sibling to [`crate::runtime`] and reuses the same Flow read-model
//! (`FlowUpdate`, `FlowNode`, `FlowEdge`) rather than redefining it. Unlike the
//! runtime, codegen never touches `BoardHandle`/Firmata — it is a pure function
//! of the input Flow.
//!
//! For this task the produced sketch is a *skeleton*: a declarations region, an
//! empty-but-valid `setup()`, and a `millis()`-based, non-blocking scheduler in
//! `loop()` (no blocking `delay()`). Per-Node C++ bodies are emitted by a later
//! task; the skeleton merely provides the slots they fill.
//!
//! ## Invariants
//!
//! - **Determinism:** identical Flow → byte-identical Sketch text. Traversal is
//!   ordered by Node `id`, never by an unordered map.
//! - **Termination:** generation always terminates, even for graphs containing
//!   cycles or disconnected Nodes — a `visited` set guards the walk.
//! - **Validity:** the output is always syntactically valid Arduino C++ and
//!   compiles even when the Flow is empty.

use crate::runtime::types::{FlowNode, FlowUpdate};
use std::collections::{BTreeMap, BTreeSet};

/// Assemble the Arduino sketch skeleton for the given Flow.
///
/// Returns the full `.ino` source as a single `String`. The traversal is
/// deterministic (Nodes visited in `id` order) and always terminates, so the
/// same Flow always yields byte-identical output.
///
/// # Errors
///
/// Never returns `Err` today — the signature is `Result` so later tasks (which
/// may fail to emit a particular Node) can surface a human-readable message to
/// the frontend without changing the contract.
pub fn generate(flow: &FlowUpdate) -> Result<String, String> {
    let order = traversal_order(flow);

    let mut sketch = String::new();
    sketch.push_str(&header(&order));
    sketch.push_str(&declarations(&order));
    sketch.push_str(SETUP);
    sketch.push_str(LOOP);

    Ok(sketch)
}

/// Deterministic traversal of the Flow.
///
/// Nodes are visited in stable `id` order; adjacency is followed depth-first
/// guarded by a `visited` set so cycles terminate. Disconnected Nodes are still
/// reached because the outer loop seeds the walk from every Node in id order.
/// The returned vector lists every Node exactly once.
fn traversal_order(flow: &FlowUpdate) -> Vec<&FlowNode> {
    let by_id: BTreeMap<&str, &FlowNode> =
        flow.nodes.iter().map(|n| (n.id.as_str(), n)).collect();

    // Adjacency keyed by source id, targets kept sorted + deduped for determinism.
    let mut adjacency: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for edge in &flow.edges {
        adjacency
            .entry(edge.source.as_str())
            .or_default()
            .insert(edge.target.as_str());
    }

    let mut visited: BTreeSet<&str> = BTreeSet::new();
    let mut order: Vec<&FlowNode> = Vec::with_capacity(by_id.len());

    // Seed from every Node in id order so disconnected Nodes are included and
    // the result is independent of edge declaration order.
    for &id in by_id.keys() {
        visit(id, &by_id, &adjacency, &mut visited, &mut order);
    }

    order
}

/// Depth-first visit guarded by `visited`; the guard is what makes cycles
/// terminate. Children are followed in sorted id order for determinism.
fn visit<'a>(
    id: &'a str,
    by_id: &BTreeMap<&'a str, &'a FlowNode>,
    adjacency: &BTreeMap<&'a str, BTreeSet<&'a str>>,
    visited: &mut BTreeSet<&'a str>,
    order: &mut Vec<&'a FlowNode>,
) {
    if !visited.insert(id) {
        return;
    }
    if let Some(node) = by_id.get(id) {
        order.push(node);
    }
    if let Some(targets) = adjacency.get(id) {
        for &target in targets {
            visit(target, by_id, adjacency, visited, order);
        }
    }
}

/// File header comment listing the Nodes the skeleton was built from. Counts
/// only; per-Node bodies arrive in a later task.
fn header(order: &[&FlowNode]) -> String {
    format!(
        "// Generated by microflow — do not edit by hand.\n// Sketch skeleton for {} node(s).\n\n",
        order.len()
    )
}

/// Declarations region. For the skeleton each Node contributes a stable comment
/// slot (in traversal order) that later emitters replace with real declarations.
fn declarations(order: &[&FlowNode]) -> String {
    let mut out = String::from("// --- Declarations ---\n");
    for node in order {
        let kind = node.node_type.as_deref().unwrap_or("unknown");
        out.push_str(&format!("// node {} ({})\n", node.id, kind));
    }
    out.push('\n');
    out
}

/// Empty-but-valid `setup()`. Per-Node init is hung off this in a later task.
const SETUP: &str = "void setup() {\n  // --- Setup ---\n}\n\n";

/// Non-blocking, `millis()`-based scheduler `loop()`. It compares `millis()`
/// against a per-tick deadline instead of calling blocking `delay()`, giving
/// timing Nodes added later a deterministic, host-free model.
const LOOP: &str = "void loop() {\n  \
static unsigned long previousMillis = 0;\n  \
const unsigned long interval = 1; // ms; non-blocking scheduler tick\n  \
unsigned long currentMillis = millis();\n  \
if (currentMillis - previousMillis >= interval) {\n    \
previousMillis = currentMillis;\n    \
// --- Scheduled tasks ---\n  \
}\n}\n";

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime::types::{FlowEdge, Position};
    use serde_json::json;

    fn node(id: &str, kind: &str) -> FlowNode {
        FlowNode {
            id: id.to_string(),
            node_type: Some(kind.to_string()),
            data: json!({}),
            position: Position { x: 0.0, y: 0.0 },
        }
    }

    fn edge(source: &str, target: &str) -> FlowEdge {
        FlowEdge {
            id: None,
            source: source.to_string(),
            target: target.to_string(),
            source_handle: "out".to_string(),
            target_handle: "in".to_string(),
        }
    }

    /// Scenario: Empty Flow yields a valid empty sketch.
    #[test]
    fn empty_flow_yields_valid_empty_sketch() {
        let flow = FlowUpdate { nodes: vec![], edges: vec![] };

        let sketch = generate(&flow).expect("empty flow must not raise an error");

        // Valid empty sketch: both required sections present.
        assert!(sketch.contains("void setup()"), "missing setup section");
        assert!(sketch.contains("void loop()"), "missing loop section");
        // No blocking delay in the scheduler.
        assert!(!sketch.contains("delay("), "skeleton must be non-blocking");
        assert!(sketch.contains("0 node(s)"), "empty flow should report zero nodes");
    }

    /// Scenario: Same Flow always produces the same sketch.
    #[test]
    fn same_flow_always_produces_the_same_sketch() {
        let flow = FlowUpdate {
            nodes: vec![node("led-1", "Led"), node("btn-1", "Button"), node("srv-1", "Servo")],
            edges: vec![edge("btn-1", "led-1"), edge("led-1", "srv-1")],
        };

        let first = generate(&flow).expect("generation should succeed");
        let second = generate(&flow).expect("generation should succeed");

        assert_eq!(first, second, "identical flow must yield byte-identical sketch");
    }

    /// Scenario: Same Flow always produces the same sketch — independent of the
    /// declaration order of nodes and edges (the determinism invariant).
    #[test]
    fn ordering_of_input_does_not_change_output() {
        let forward = FlowUpdate {
            nodes: vec![node("a", "Led"), node("b", "Button"), node("c", "Sensor")],
            edges: vec![edge("a", "b"), edge("b", "c")],
        };
        let shuffled = FlowUpdate {
            nodes: vec![node("c", "Sensor"), node("a", "Led"), node("b", "Button")],
            edges: vec![edge("b", "c"), edge("a", "b")],
        };

        assert_eq!(
            generate(&forward).unwrap(),
            generate(&shuffled).unwrap(),
            "output must depend on graph content, not declaration order"
        );
    }

    /// Scenario: A graph with a cycle terminates deterministically.
    #[test]
    fn graph_with_cycle_terminates_deterministically() {
        let flow = FlowUpdate {
            nodes: vec![node("a", "Led"), node("b", "Button"), node("c", "Relay")],
            // a -> b -> c -> a forms a cycle.
            edges: vec![edge("a", "b"), edge("b", "c"), edge("c", "a")],
        };

        // If traversal did not guard with a visited set this would loop forever;
        // the test completing at all proves termination.
        let first = generate(&flow).expect("cycle must not loop forever");
        let second = generate(&flow).expect("cycle must not loop forever");

        assert_eq!(first, second, "cyclic flow must still be deterministic");
        // Every node appears exactly once despite the cycle.
        assert_eq!(first.matches("// node ").count(), 3, "each node emitted once");
    }

    /// Scenario: Disconnected Nodes do not break generation.
    #[test]
    fn disconnected_nodes_do_not_break_generation() {
        let flow = FlowUpdate {
            nodes: vec![node("a", "Led"), node("b", "Button"), node("lonely", "Sensor")],
            // "lonely" is connected to nothing.
            edges: vec![edge("a", "b")],
        };

        let sketch = generate(&flow).expect("disconnected node must not break generation");

        assert!(sketch.contains("void setup()"));
        assert!(sketch.contains("void loop()"));
        // The disconnected node is still handled (deterministically reached via
        // the id-ordered seed loop).
        assert!(sketch.contains("// node lonely (Sensor)"), "disconnected node missing");
        assert_eq!(sketch.matches("// node ").count(), 3, "all nodes emitted once");
    }
}
