//! Sketch Generation context — translate a Flow graph ahead-of-time into an
//! Arduino sketch (`.ino` source).
//!
//! This module is the entry point of the Sketch Generation context. It sits as
//! a sibling to [`crate::runtime`] and reuses the same Flow read-model
//! (`FlowUpdate`, `FlowNode`, `FlowEdge`) rather than redefining it. Unlike the
//! runtime, codegen never touches `BoardHandle`/Firmata — it is a pure function
//! of the input Flow.
//!
//! For this task the produced sketch is a *skeleton*: a declarations region, an
//! empty-but-valid `setup()`, and a `millis()`-based, non-blocking scheduler in
//! `loop()` (no blocking `delay()`). Per-Node C++ bodies are emitted by a later
//! task; the skeleton merely provides the slots they fill.
//!
//! ## Invariants
//!
//! - **Determinism:** identical Flow → byte-identical Sketch text. Traversal is
//!   ordered by Node `id`, never by an unordered map.
//! - **Termination:** generation always terminates, even for graphs containing
//!   cycles or disconnected Nodes — a `visited` set guards the walk.
//! - **Validity:** the output is always syntactically valid Arduino C++ and
//!   compiles even when the Flow is empty.

pub mod board;
pub mod emit;
pub mod input;
pub mod output;
pub mod placeholder;

use crate::runtime::types::{FlowNode, FlowUpdate};
use emit::NodeEmission;
use std::collections::{BTreeMap, BTreeSet};

/// Assemble the Arduino sketch skeleton for the given Flow.
///
/// Returns the full `.ino` source as a single `String`. The traversal is
/// deterministic (Nodes visited in `id` order) and always terminates, so the
/// same Flow always yields byte-identical output.
///
/// # Errors
///
/// Never returns `Err` today — the signature is `Result` so later tasks (which
/// may fail to emit a particular Node) can surface a human-readable message to
/// the frontend without changing the contract.
pub fn generate(flow: &FlowUpdate) -> Result<String, String> {
    let order = traversal_order(flow);
    let drivers = driver_expressions(flow);

    // Emit each Node in deterministic traversal order, collecting fragments.
    let emissions: Vec<NodeEmission> =
        order.iter().map(|node| emit_node(node, &drivers)).collect();

    let emitted_count = emissions.iter().filter(|e| !e.is_empty()).count();
    log::debug!(
        "codegen: emitted {emitted_count} of {} node(s)",
        order.len()
    );

    let mut sketch = String::new();
    sketch.push_str(&header(&order));
    sketch.push_str(&includes_region(&emissions));
    sketch.push_str(&declarations(&order, &emissions));
    sketch.push_str(&setup_region(&emissions));
    sketch.push_str(&loop_region(&emissions));

    Ok(sketch)
}

/// Deterministic traversal of the Flow.
///
/// Nodes are visited in stable `id` order; adjacency is followed depth-first
/// guarded by a `visited` set so cycles terminate. Disconnected Nodes are still
/// reached because the outer loop seeds the walk from every Node in id order.
/// The returned vector lists every Node exactly once.
fn traversal_order(flow: &FlowUpdate) -> Vec<&FlowNode> {
    let by_id: BTreeMap<&str, &FlowNode> =
        flow.nodes.iter().map(|n| (n.id.as_str(), n)).collect();

    // Adjacency keyed by source id, targets kept sorted + deduped for determinism.
    let mut adjacency: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for edge in &flow.edges {
        adjacency
            .entry(edge.source.as_str())
            .or_default()
            .insert(edge.target.as_str());
    }

    let mut visited: BTreeSet<&str> = BTreeSet::new();
    let mut order: Vec<&FlowNode> = Vec::with_capacity(by_id.len());

    // Seed from every Node in id order so disconnected Nodes are included and
    // the result is independent of edge declaration order.
    for &id in by_id.keys() {
        visit(id, &by_id, &adjacency, &mut visited, &mut order);
    }

    order
}

/// Depth-first visit guarded by `visited`; the guard is what makes cycles
/// terminate. Children are followed in sorted id order for determinism.
fn visit<'a>(
    id: &'a str,
    by_id: &BTreeMap<&'a str, &'a FlowNode>,
    adjacency: &BTreeMap<&'a str, BTreeSet<&'a str>>,
    visited: &mut BTreeSet<&'a str>,
    order: &mut Vec<&'a FlowNode>,
) {
    if !visited.insert(id) {
        return;
    }
    if let Some(node) = by_id.get(id) {
        order.push(node);
    }
    if let Some(targets) = adjacency.get(id) {
        for &target in targets {
            visit(target, by_id, adjacency, visited, order);
        }
    }
}

/// File header comment listing the Nodes the skeleton was built from. Counts
/// only; per-Node bodies arrive in a later task.
fn header(order: &[&FlowNode]) -> String {
    format!(
        "// Generated by microflow — do not edit by hand.\n// Sketch skeleton for {} node(s).\n\n",
        order.len()
    )
}

/// Dispatch a single Node to its per-type C++ emitter, mirroring the live
/// `ComponentRegistry`. Node types outside the supported core hardware-IO set
/// (Cloud Nodes like Mqtt/Figma/Llm/Monitor, unknown types, and typeless
/// Nodes) fall through to [`placeholder::emit`], which returns a graceful
/// comment fragment so generation never crashes or blanks the sketch.
/// `drivers` maps a target Node id to the C++ expression that drives it (from
/// its wired source), so output Nodes write what their input reads.
fn emit_node(node: &FlowNode, drivers: &BTreeMap<&str, String>) -> NodeEmission {
    let driver = drivers.get(node.id.as_str()).map(String::as_str);
    match node.node_type.as_deref() {
        Some("Led") => output::led::emit(node, driver),
        Some("Relay") => output::relay::emit(node, driver),
        Some("Servo") => output::servo::emit(node, driver),
        Some("Button") => input::button::emit(node),
        Some("Sensor") => input::sensor::emit(node),
        _ => placeholder::emit(node),
    }
}

/// Build the map from a target Node id to the C++ expression that drives it.
///
/// An output Node (Led/Relay/Servo) wired from an input Node (Button/Sensor)
/// reads that input's state/value variable. When a target has multiple incoming
/// edges, the source with the smallest id wins, keeping the result
/// deterministic. Edges from sources that expose no readable expression are
/// ignored.
fn driver_expressions(flow: &FlowUpdate) -> BTreeMap<&str, String> {
    let by_id: BTreeMap<&str, &FlowNode> =
        flow.nodes.iter().map(|n| (n.id.as_str(), n)).collect();

    // For determinism, choose the smallest source id per target.
    let mut chosen: BTreeMap<&str, &str> = BTreeMap::new();
    for edge in &flow.edges {
        let target = edge.target.as_str();
        let source = edge.source.as_str();
        chosen
            .entry(target)
            .and_modify(|s| {
                if source < *s {
                    *s = source;
                }
            })
            .or_insert(source);
    }

    chosen
        .into_iter()
        .filter_map(|(target, source)| {
            let src_node = by_id.get(source)?;
            source_expression(src_node).map(|expr| (target, expr))
        })
        .collect()
}

/// The C++ expression a source Node exposes for downstream Nodes to read, or
/// `None` if the Node type produces no readable value.
fn source_expression(node: &FlowNode) -> Option<String> {
    match node.node_type.as_deref() {
        Some("Button") => Some(input::button::state_var(node)),
        Some("Sensor") => Some(input::sensor::value_var(node)),
        _ => None,
    }
}

/// Deduplicated `#include` block, sorted for determinism.
fn includes_region(emissions: &[NodeEmission]) -> String {
    let includes: BTreeSet<&str> = emissions
        .iter()
        .flat_map(|e| e.includes.iter().map(String::as_str))
        .collect();
    if includes.is_empty() {
        return String::new();
    }
    let mut out = String::from("// --- Includes ---\n");
    for inc in includes {
        out.push_str(inc);
        out.push('\n');
    }
    out.push('\n');
    out
}

/// Declarations region. Each Node gets a labelled comment slot followed by its
/// real declarations (in traversal order) so output is stable and readable.
fn declarations(order: &[&FlowNode], emissions: &[NodeEmission]) -> String {
    let mut out = String::from("// --- Declarations ---\n");
    for (node, emission) in order.iter().zip(emissions) {
        let kind = node.node_type.as_deref().unwrap_or("unknown");
        out.push_str(&format!("// node {} ({})\n", node.id, kind));
        for line in &emission.declarations {
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push('\n');
    out
}

/// `setup()` with each Node's init statements stitched in (traversal order).
fn setup_region(emissions: &[NodeEmission]) -> String {
    let mut out = String::from("void setup() {\n  // --- Setup ---\n");
    for line in emissions.iter().flat_map(|e| &e.setup) {
        out.push_str("  ");
        out.push_str(line);
        out.push('\n');
    }
    out.push_str("}\n\n");
    out
}

/// Non-blocking, `millis()`-based scheduler `loop()`. It compares `millis()`
/// against a per-tick deadline instead of calling blocking `delay()`, giving a
/// deterministic, host-free model. Per-Node read/write logic runs inside the
/// scheduled-task block in traversal order.
fn loop_region(emissions: &[NodeEmission]) -> String {
    let mut out = String::from(
        "void loop() {\n  \
static unsigned long previousMillis = 0;\n  \
const unsigned long interval = 1; // ms; non-blocking scheduler tick\n  \
unsigned long currentMillis = millis();\n  \
if (currentMillis - previousMillis >= interval) {\n    \
previousMillis = currentMillis;\n    \
// --- Scheduled tasks ---\n",
    );
    for line in emissions.iter().flat_map(|e| &e.loop_body) {
        out.push_str("    ");
        out.push_str(line);
        out.push('\n');
    }
    out.push_str("  }\n}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime::types::{FlowEdge, Position};
    use serde_json::json;

    fn node(id: &str, kind: &str) -> FlowNode {
        FlowNode {
            id: id.to_string(),
            node_type: Some(kind.to_string()),
            data: json!({}),
            position: Position { x: 0.0, y: 0.0 },
        }
    }

    fn node_data(id: &str, kind: &str, data: serde_json::Value) -> FlowNode {
        FlowNode {
            id: id.to_string(),
            node_type: Some(kind.to_string()),
            data,
            position: Position { x: 0.0, y: 0.0 },
        }
    }

    fn edge(source: &str, target: &str) -> FlowEdge {
        FlowEdge {
            id: None,
            source: source.to_string(),
            target: target.to_string(),
            source_handle: "out".to_string(),
            target_handle: "in".to_string(),
        }
    }

    /// Scenario: Empty Flow yields a valid empty sketch.
    #[test]
    fn empty_flow_yields_valid_empty_sketch() {
        let flow = FlowUpdate { nodes: vec![], edges: vec![] };

        let sketch = generate(&flow).expect("empty flow must not raise an error");

        // Valid empty sketch: both required sections present.
        assert!(sketch.contains("void setup()"), "missing setup section");
        assert!(sketch.contains("void loop()"), "missing loop section");
        // No blocking delay in the scheduler.
        assert!(!sketch.contains("delay("), "skeleton must be non-blocking");
        assert!(sketch.contains("0 node(s)"), "empty flow should report zero nodes");
    }

    /// Scenario: Same Flow always produces the same sketch.
    #[test]
    fn same_flow_always_produces_the_same_sketch() {
        let flow = FlowUpdate {
            nodes: vec![node("led-1", "Led"), node("btn-1", "Button"), node("srv-1", "Servo")],
            edges: vec![edge("btn-1", "led-1"), edge("led-1", "srv-1")],
        };

        let first = generate(&flow).expect("generation should succeed");
        let second = generate(&flow).expect("generation should succeed");

        assert_eq!(first, second, "identical flow must yield byte-identical sketch");
    }

    /// Scenario: Same Flow always produces the same sketch — independent of the
    /// declaration order of nodes and edges (the determinism invariant).
    #[test]
    fn ordering_of_input_does_not_change_output() {
        let forward = FlowUpdate {
            nodes: vec![node("a", "Led"), node("b", "Button"), node("c", "Sensor")],
            edges: vec![edge("a", "b"), edge("b", "c")],
        };
        let shuffled = FlowUpdate {
            nodes: vec![node("c", "Sensor"), node("a", "Led"), node("b", "Button")],
            edges: vec![edge("b", "c"), edge("a", "b")],
        };

        assert_eq!(
            generate(&forward).unwrap(),
            generate(&shuffled).unwrap(),
            "output must depend on graph content, not declaration order"
        );
    }

    /// Scenario: A graph with a cycle terminates deterministically.
    #[test]
    fn graph_with_cycle_terminates_deterministically() {
        let flow = FlowUpdate {
            nodes: vec![node("a", "Led"), node("b", "Button"), node("c", "Relay")],
            // a -> b -> c -> a forms a cycle.
            edges: vec![edge("a", "b"), edge("b", "c"), edge("c", "a")],
        };

        // If traversal did not guard with a visited set this would loop forever;
        // the test completing at all proves termination.
        let first = generate(&flow).expect("cycle must not loop forever");
        let second = generate(&flow).expect("cycle must not loop forever");

        assert_eq!(first, second, "cyclic flow must still be deterministic");
        // Every node appears exactly once despite the cycle.
        assert_eq!(first.matches("// node ").count(), 3, "each node emitted once");
    }

    /// Scenario: Disconnected Nodes do not break generation.
    #[test]
    fn disconnected_nodes_do_not_break_generation() {
        let flow = FlowUpdate {
            nodes: vec![node("a", "Led"), node("b", "Button"), node("lonely", "Sensor")],
            // "lonely" is connected to nothing.
            edges: vec![edge("a", "b")],
        };

        let sketch = generate(&flow).expect("disconnected node must not break generation");

        assert!(sketch.contains("void setup()"));
        assert!(sketch.contains("void loop()"));
        // The disconnected node is still handled (deterministically reached via
        // the id-ordered seed loop).
        assert!(sketch.contains("// node lonely (Sensor)"), "disconnected node missing");
        assert_eq!(sketch.matches("// node ").count(), 3, "all nodes emitted once");
    }

    /// Scenario: A core hardware-IO Flow produces a compilable sketch.
    ///
    /// A Flow using all five supported Node types must emit pin setup and
    /// read/write logic for each, inside a structurally valid sketch.
    #[test]
    fn core_hardware_io_flow_emits_setup_and_io_for_each_node() {
        let flow = FlowUpdate {
            nodes: vec![
                node_data("led-1", "Led", json!({ "pin": 13 })),
                node_data("btn-1", "Button", json!({ "pin": 6 })),
                node_data("sensor-1", "Sensor", json!({ "pin": "A0" })),
                node_data("servo-1", "Servo", json!({ "pin": 9 })),
                node_data("relay-1", "Relay", json!({ "pin": 10 })),
            ],
            edges: vec![edge("btn-1", "led-1"), edge("sensor-1", "servo-1")],
        };

        let sketch = generate(&flow).expect("generation should succeed");

        // Structurally valid sketch.
        assert!(sketch.contains("void setup()"));
        assert!(sketch.contains("void loop()"));
        assert!(!sketch.contains("delay("), "must stay non-blocking");

        // Pin setup for each Node.
        assert!(sketch.contains("pinMode") && sketch.contains("OUTPUT"), "led/relay OUTPUT setup");
        assert!(sketch.contains("INPUT"), "button INPUT setup");
        // Read/write logic present.
        assert!(sketch.contains("digitalWrite"), "led/relay write");
        assert!(sketch.contains("digitalRead"), "button read");
        assert!(sketch.contains("analogRead"), "sensor read");
        assert!(sketch.contains(".attach("), "servo attach");
        assert!(sketch.contains("#include <Servo.h>"), "servo include");
    }

    /// Scenario: A Button drives a Led through an edge.
    #[test]
    fn button_drives_led_through_an_edge() {
        let flow = FlowUpdate {
            nodes: vec![
                node_data("led-1", "Led", json!({ "pin": 13 })),
                node_data("btn-1", "Button", json!({ "pin": 6 })),
            ],
            edges: vec![edge("btn-1", "led-1")],
        };

        let sketch = generate(&flow).expect("generation should succeed");

        // The Button reads its input into a state var.
        assert!(sketch.contains("button_btn_1_state = "), "button read into state var");
        assert!(sketch.contains("digitalRead"), "button digitalRead");
        // The Led writes that state.
        assert!(
            sketch.contains("digitalWrite(led_led_1_pin, (button_btn_1_state)"),
            "led must be driven by the button state, got:\n{sketch}"
        );
    }

    /// Scenario: A Servo Node pulls in its supporting library.
    #[test]
    fn servo_node_pulls_in_its_library() {
        let flow = FlowUpdate {
            nodes: vec![node_data("servo-1", "Servo", json!({ "pin": 9 }))],
            edges: vec![],
        };

        let sketch = generate(&flow).expect("generation should succeed");

        assert!(sketch.contains("#include <Servo.h>"), "missing Servo include");
        assert!(sketch.contains("Servo servo_servo_1"), "missing Servo object decl");
        assert!(sketch.contains(".attach(servo_servo_1_pin)"), "missing attach to pin");
    }

    /// The Servo include appears only when a Servo Node is present.
    #[test]
    fn no_servo_include_without_a_servo_node() {
        let flow = FlowUpdate {
            nodes: vec![node_data("led-1", "Led", json!({ "pin": 13 }))],
            edges: vec![],
        };
        let sketch = generate(&flow).expect("generation should succeed");
        assert!(!sketch.contains("Servo.h"), "no servo include without a servo node");
    }

    /// Scenario: Each supported Node type emits deterministic code — full Flow.
    #[test]
    fn full_flow_emits_deterministically() {
        let flow = FlowUpdate {
            nodes: vec![
                node_data("led-1", "Led", json!({ "pin": 13 })),
                node_data("btn-1", "Button", json!({ "pin": 6, "isPullup": true })),
                node_data("servo-1", "Servo", json!({ "pin": 9 })),
            ],
            edges: vec![edge("btn-1", "led-1")],
        };
        assert_eq!(generate(&flow).unwrap(), generate(&flow).unwrap());
    }

    /// Scenario: An unsupported Node becomes a placeholder comment.
    ///
    /// A Cloud Node (Mqtt) alongside a core Led: the Cloud Node gets a clear
    /// placeholder comment, the Led still emits real code, and generation does
    /// not crash or blank the sketch.
    #[test]
    fn cloud_node_becomes_placeholder_while_core_node_still_emits() {
        let flow = FlowUpdate {
            nodes: vec![
                node("mqtt-1", "Mqtt"),
                node_data("led-1", "Led", json!({ "pin": 13 })),
            ],
            edges: vec![],
        };

        let sketch = generate(&flow).expect("cloud node must not crash generation");

        // Placeholder for the Cloud Node, identifying it and the networked need.
        assert!(
            sketch.contains("// unsupported Node mqtt_1 (Mqtt)"),
            "missing Mqtt placeholder, got:\n{sketch}"
        );
        assert!(sketch.contains("networked target"), "Cloud message missing");
        // The Led still produces real code.
        assert!(sketch.contains("pinMode"), "led pin setup missing");
        assert!(sketch.contains("digitalWrite"), "led write missing");
        // Sketch is not blanked.
        assert!(sketch.contains("void setup()") && sketch.contains("void loop()"));
    }

    /// Scenario: An unknown Node type does not break generation.
    #[test]
    fn unknown_node_type_does_not_break_generation() {
        let flow = FlowUpdate {
            nodes: vec![
                node("gizmo-1", "Gizmo"),
                node_data("led-1", "Led", json!({ "pin": 13 })),
            ],
            edges: vec![],
        };

        let sketch = generate(&flow).expect("unknown node must not crash generation");

        assert!(
            sketch.contains("// unsupported Node gizmo_1 (Gizmo)"),
            "missing unknown-type placeholder, got:\n{sketch}"
        );
        // The rest of the sketch is still produced.
        assert!(sketch.contains("digitalWrite"), "led code still produced");
        assert!(sketch.contains("void loop()"));
    }

    /// Scenario: A Flow of only unsupported Nodes still yields a valid sketch.
    #[test]
    fn all_unsupported_flow_yields_valid_sketch() {
        let flow = FlowUpdate {
            nodes: vec![
                node("mqtt-1", "Mqtt"),
                node("figma-1", "Figma"),
                node("llm-1", "Llm"),
                node("monitor-1", "Monitor"),
            ],
            edges: vec![],
        };

        let sketch = generate(&flow).expect("all-unsupported flow must not raise an error");

        // A structurally valid sketch is still produced.
        assert!(sketch.contains("void setup()"), "missing setup section");
        assert!(sketch.contains("void loop()"), "missing loop section");
        // A placeholder for every unsupported Node.
        assert_eq!(
            sketch.matches("// unsupported Node ").count(),
            4,
            "expected one placeholder per unsupported node, got:\n{sketch}"
        );
    }

    /// Scenario: Placeholder comments are deterministic.
    #[test]
    fn placeholder_comments_are_deterministic_at_sketch_level() {
        let flow = FlowUpdate {
            nodes: vec![node("mqtt-1", "Mqtt"), node("gizmo-1", "Gizmo")],
            edges: vec![],
        };

        let first = generate(&flow).expect("generation should succeed");
        let second = generate(&flow).expect("generation should succeed");

        assert_eq!(
            first, second,
            "repeated generation must yield identical placeholder comments"
        );
    }
}
